'use client';

import { useEffect } from 'react';

export default function ChatBotTermsModal({ open, onAccept, onDecline }) {
  // Lock background scroll when modal is open
  useEffect(() => {
    if (open) document.body.style.overflow = 'hidden';
    return () => {
      document.body.style.overflow = 'auto';
    };
  }, [open]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm px-4">
      <div className="relative max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-xl bg-white shadow-xl dark:bg-neutral-900">

        {/* Header */}
        <div className="flex items-center justify-between border-b px-6 py-4 dark:border-neutral-800">
          <h2 className="text-lg font-semibold">
            User Warning and Agreement
          </h2>

          <button
            onClick={onDecline}
            aria-label="Close"
            className="rounded-md p-1 text-neutral-500 hover:bg-neutral-100 hover:text-neutral-700 dark:hover:bg-neutral-800"
          >
            ✕
          </button>
        </div>

        {/* Content */}
        <div className="max-h-[65vh] overflow-y-auto px-6 py-4 text-sm text-neutral-700 dark:text-neutral-300 space-y-4">
          <p className="font-medium text-neutral-900 dark:text-neutral-100">
            PLEASE READ CAREFULLY BEFORE USING THIS TOOL
          </p>

          <Section title="1. No Legal Advice">
            This Tool is provided for informational and assistive purposes only.
            It does not provide legal advice, medical advice, or professional
            services of any kind. Use of this Tool does not create an
            attorney-client relationship or any other professional relationship.
          </Section>

          <Section title="2. Accuracy and Limitations of AI">
            Artificial intelligence systems may produce incomplete, outdated, or
            incorrect information. You understand and agree that:
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Outputs generated by the Tool may contain errors</li>
              <li>
                You are solely responsible for reviewing, verifying, and
                validating all outputs before relying on them
              </li>
              <li>
                The Tool should not be relied upon as a sole source for decisions
                affecting legal rights, benefits, or claims
              </li>
            </ul>
          </Section>

          <Section title="3. User Responsibility for Uploaded Documents">
            You are solely responsible for any documents or data you upload,
            including VA decisions or other records. By using the Tool, you
            represent that:
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>You have the legal right and authority to upload the documents</li>
              <li>
                You are not uploading documents in violation of any law,
                regulation, or duty of confidentiality
              </li>
              <li>
                You understand the risks of uploading sensitive or personal
                information
              </li>
            </ul>
          </Section>

          <Section title="4. Sensitive and Personal Information">
            Uploaded documents may contain sensitive personal information. By
            proceeding, you acknowledge that:
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>You assume all risks associated with uploading such information</li>
              <li>You are responsible for redacting information if you choose to do so</li>
              <li>
                The Tool is provided “as-is” and without guarantees regarding
                confidentiality beyond applicable law and stated policies
              </li>
            </ul>
          </Section>

          <Section title="5. No Guarantees or Warranties">
            The Tool is provided without warranties of any kind, express or
            implied, including but not limited to accuracy, reliability,
            fitness for a particular purpose, or availability.
          </Section>

          <Section title="6. Limitation of Liability">
            To the maximum extent permitted by law, the provider of this Tool
            shall not be liable for any damages, losses, or consequences arising
            from:
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use or misuse of the Tool</li>
              <li>Reliance on AI-generated outputs</li>
              <li>Uploading or handling of documents through the Tool</li>
            </ul>
          </Section>

          <Section title="7. Acceptance of Terms">
            By clicking “I Agree”, continuing to use the Tool, or uploading
            documents, you confirm that:
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>You have read and understood this Warning and Agreement</li>
              <li>You voluntarily accept these terms</li>
              <li>You agree to use the Tool at your own risk</li>
            </ul>
          </Section>
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-3 border-t px-6 py-4 dark:border-neutral-800">
          {/* <button
            onClick={onDecline}
            className="rounded-md px-4 py-2 text-sm text-neutral-700 hover:bg-neutral-100 dark:text-neutral-300 dark:hover:bg-neutral-800"
          >
            Decline
          </button> */}

          <button
            onClick={onAccept}
            className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700"
          >
            I Agree
          </button>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <p className="font-semibold text-neutral-900 dark:text-neutral-100">
        {title}
      </p>
      <div className="mt-1">{children}</div>
    </div>
  );
}
