export const SubmitIntentFileMap = {
  firstName: 'First Name',
  lastName: 'Last Name',
  ssn: 'SSN (Social Security Number)',
  claim: 'Claim',
  currentVa: 'VA File No.',
  birthday: 'Birthday',
  serviceNumber: 'Service Number',
  street: 'Street',
  unitNumber: 'Unit Number',
  city: 'City',
  province: 'Province',
  country: 'US',
  zipCode: 'Zip Code',
  phone: 'Phone No.',
  phoneI: 'International Phone No.',
  email: 'Email',
  emailE: 'Electronic Correspondence',
  claimantsName: 'Claimants First Name',
  claimantsLastName: 'Claimants Last Name',
  claimantsSsn: 'Claimants SSN',
  claimantsClaim: 'Claimants Claim',
  claimantsCurrentVa: 'Claimants VA File No.',
  claimantsRelationship: 'Claimants Relationship',
  claimantOther: 'Claimants Other',
  claimantsStreet: 'Claimants Street',
  claimantsUnitNumber: 'Claimants Unit Number',
  claimantsCity: 'Claimants City',
  claimantsProvince: 'Claimants Province',
  claimantsCountry: 'US',
  claimantsZipCode: 'Claimants Zip Code',
  claimantsPhone: 'Claimants Phone No.',
  claimantsPhoneI: 'Claimants International Phone No.',
  claimantsEmail: 'Claimants Email',
  claimantsEmailE: 'Claimants Electronic Correspondence',
  veteranDateSigned: 'Date Signed (21 of 21)',
  benefitElection: 'Benefit Election',
  signature: 'Add Signature on your Profile',
};
