export const SubmitIntentFileMap = {
  firstName: 'First Name',
  lastName: 'Last Name',
  ssn: 'SSN (Social Security Number)',
  claim: 'Claim',
  currentVa: 'VA File No.',
  birthday: 'Birthday',
  serviceNumber: 'Service Number',
  street: 'Street',
  unitNumber: 'Unit Number',
  city: 'City',
  province: 'Province',
  country: 'US',
  zipCode: 'Zip Code',
  phone: 'Phone No.',
  phoneI: 'International Phone No.',
  email: 'Email',
  emailE: 'Electronic Correspondence',
  claimantsName: 'Claimants First Name',
  claimantsLastName: 'Claimants Last Name',
  claimantsSsn: 'Claimants SSN',
  claimantsClaim: 'Claimants Claim',
  claimantsCurrentVa: 'Claimants VA File No.',
  claimantsRelationship: 'Claimants Relationship',
  claimantOther: 'Claimants Other',
  claimantsStreet: 'Claimants Street',
  claimantsUnitNumber: 'Claimants Unit Number',
  claimantsCity: 'Claimants City',
  claimantsProvince: 'Claimants Province',
  claimantsCountry: 'US',
  claimantsZipCode: 'Claimants Zip Code',
  claimantsPhone: 'Claimants Phone No.',
  claimantsPhoneI: 'Claimants International Phone No.',
  claimantsEmail: 'Claimants Email',
  claimantsEmailE: 'Claimants Electronic Correspondence',
  veteranDateSigned: 'Date Signed (21 of 21)',
  benefitElection: 'Benefit Election',
  signature: 'Add Signature on your Profile',
};

export const NewClaimFileMap = {
  program: 'Program',
  firstName: 'First Name',
  lastName: 'Last Name',
  ssn: 'SSN (Social Security Number)',
  claim: 'Claim',
  currentVa: 'Current VA File',
  birthday: 'Birthday',
  serviceNumber: 'Service Number',
  street: 'Street',
  unitNumber: 'Unit Number',
  city: 'City',
  province: 'Province',
  country: 'US',
  zipCode: 'Zip Code',
  phone: 'Phone',
  phoneI: 'International Phone Number',
  emailE: 'Electronic Correspondence',
  //new_fields,
  bddDate: 'BDD Claims',
  email: 'Email',
  currentlyEmployee: 'Currently a VA Employee',
  //section II, new address
  typeAddressChange: 'Address Change',
  newAddressstreet: 'New Address Street',
  newAddressunitNumber: 'New Address Unit Number',
  newAddresscity: 'New Address City',
  newAddressprovince: 'New Address Province',
  newAddresscountry: 'US',
  newAddresszipCode: 'New Address ZIP Code',
  newAddressEffectiveBeginning: 'New Address Effective Beginning',
  newAddressEffectiveEnding: 'New Address Effective Ending',
  //section III, homeless,
  currentlyHomeless: 'Homelessness',
  currentlyHomelesslivingSituation: 'Living Situation',
  currentlyHomelessspecify: 'Specify Homelessness',
  riskOfHomeless: 'Risk Of Homelessness',
  riskOfHomelesslivingSituation: 'Living Situation',
  riskOfHomelessspecify: 'Specify Risk Of Homelessness',
  pointOfContactName: 'Point Of Contact',
  pointOfContactTelephone: 'Point Of Contact Phone No.',
  pointOfContactTelephoneI: 'Point Of Contact Int. Phone No.',
  //Exposure Information
  toxicExposures: 'Toxic Exposures',
  //Claim info
  disabilities: 'Disabilities',
  treatmentFacilities: 'Treatment Facilities',
  //Service Information
  anotherName: 'Another Name',
  anotherNamenamesList: 'Another Names List',
  branchOfService: 'Branch Of Service',
  component: 'Component',
  recentDatesFrom: 'Recent Dates From',
  recentDatesTo: 'Recent Dates To',
  placeOfSeparation: 'Place Of Separation',
  combatZone: 'Combat Zone',
  combatZoneDateFrom: 'Combat Zone Date From',
  combatZoneDateTo: 'Combat Zone Date To',
  reservesNationalGuard: 'Reserves National Guard',
  reservesNationalGuardComponent: 'Reserves National Guard Component',
  reservesNationalGuardDateFrom: 'Reserves National Guard Date From',
  reservesNationalGuardDateTo: 'Reserves National Guard Date To',
  reservesNationalGuardNameAddressUnit: 'Reserves National Guard Address Unit',
  reservesNationalGuardPhoneNumber: 'Reserves National Guard Phone No.',
  reservesNationalGuardTrainingPay: 'Reserves National Guard Training Pay',
  federalsOrders: 'Federal Orders',
  federalsOrdersActivationDate: 'Federal Orders Activation Date',
  federalsOrdersSeparationDate: 'Federal Orders Separation Date',
  prisionerOfWar: 'Prisoner Of War',
  prisionerOfWarOneDateFrom: 'Prisoner Of War Date From (1)',
  prisionerOfWarOneDateTo: 'Prisoner Of War Date To (1)',
  prisionerOfWarTwoDateFrom: 'Prisoner Of War Date From (2)',
  prisionerOfWarTwoDateTo: 'Prisoner Of War Date To (1)',

  //Section VII
  retiredPay: 'Retired Pay',
  retiredPayFuture: 'Retired Pay in Future',
  retiredPayExplanation: 'Retired Pay Explanation',
  retiredPayBranchOfService: 'Retired Pay Branch Of Service',
  retiredPayMonthlyAmount: 'Retired Pay Monthly Amount',
  retiredPayRetiredStatus: 'Retired Pay Retired Status',
  noRetiredPayment: 'No Retired Payment',
  separationPay: 'Separation Pay',
  separationPayPaymentDate: 'Separation Pay Payment Date',
  separationPayBranchOfService: 'Separation Pay Branch Of Service',
  separationPayAmountReceived: 'Separation Pay Amount Received',
  noInactivePayment: 'No Inactive Payment',
  directDeposit: 'Direct Deposit',
  veteranDateSigned: 'Date Signed',
  signature: 'Add Signature on your Profile',
};

export const CourtFormFileMap = {
  boardDecisionDate: 'Board Decision Date',
  appeallantName: 'Appeallant Name',
  appeallantSsn: 'Appeallant SSN',
  appeallantAddress: 'Appeaellant Address',
  phone: 'Phone',
  email: 'Email',
  relationshipToAppeallant: 'Relationship To Appeallant',
  receiveEmail: 'Receive Email?',
  selectedAppearance: 'Selected Appearance',
  personFillingSignatureDateSigned: 'Person Filling Signature Date Signed',
  financialHardship: 'Financial Hardship',
  hardshipDocketNo: 'Hardship Docket No.',
  hardshipAppeallant: 'Hardship Appeallant',
  hardshipSignatureOfAppeallant: 'Hardship Signature Of Appeallant',
  hardshipDateSignedAppeallant: 'Hardship Date Signed Appeallant',
  hardshipPhone: 'Hardship Phone',
  hardshipEmail: 'Hardship Email',
  signature: 'Add Signature on your Profile',
};

export const FinancialHardshipFileMap = {
  docketNo: 'Docket No.',
  appeallant: 'Appeallant',
  signatureOfAppeallant: 'Signature Of Appeallant',
  dateSignedAppeallant: 'Date Signed',
  phone: 'Phone',
  email: 'Email',
  signature: 'Add Signature on your Profile',
};


export const RequestCFileMap = {
  firstName: 'First Name',
  lastName: 'Last Name',
  ssn: 'SSN (Social Security Number)',
  currentVa: 'VA File Number',
  alien: 'Alien registration number',
  birthday: 'Birthday',
  placeBirth: 'Birth Place',
  street: 'Street',
  unitNumber: 'Unit Number',
  city: 'City',
  province: 'Province',
  country: 'US',
  zipCode: 'Zip Code',
  phone: 'Phone',
  phoneI: 'Int. Phone No.',
  fax: 'Fax',
  faxI: 'Int. Fax No.',
  email: 'Email',
  emailE: 'Electronic Correspondence',
  firstNameTwo: 'First Name (2)',
  lastNameTwo: 'Last Name (2)',
  organization: 'Organization',
  streetTwo: 'Street (2)',
  unitNumberTwo: 'Unit Number (2)',
  cityTwo: 'City (2)',
  provinceTwo: 'Province (2)',
  countryTwo: 'US',
  zipCodeTwo: 'Zip Code (2)',
  phoneTwo: 'Phone (2)',
  phoneITwo: 'Int. Phone No. (2)',
  faxTwo: 'Fax (2)',
  faxITwo: 'Int. Fax No. (2)',
  firstNameThree: 'First Name (3)',
  lastNameThree: 'Last Name (3)',
  ssnThree: 'SSN (3)',
  alienThree: 'Alien (3)',
  currentVaThree: 'Current VA (3)',
  typeOfRecords: 'Type of Records',
  remarks: 'Remarks',
  checkApplicableFees: 'Check Applicable Fees',
  amount: 'Amount',
  checkFeeWaiver: 'Check Fee Waiver',
  feeWaiver: 'Fee Waiver',
  ssnWillingnessToPay: 'SSN Willingness To Pay',
  dateSignedOne: 'Date Signed (1)',
  dateSignedTwo: 'Date Signed (2)',
  dateSignedThree: 'Date Signed (3)',
  signature: 'Add Signature on your Profile',
};


export const SupplementalClaimFileMap = {
  firstName: 'First Name',
  lastName: 'Last Name',
  ssn: 'SSN (Social Security Number)',
  currentVa: 'VA File Number',
  birthday: 'Birthday',
  serviceNumber: 'Service Number',
  insuranceNumber: 'Insurance Number',
  claimantsName: 'Claimants Name',
  claimantsLastName: 'Claimants Last Name',
  claimantsRelationship: 'Claimants Relationship',
  claimantsRelationshipOther: 'Claimants Relationship (Other)',
  street: 'Street',
  unitNumber: 'Unit Number',
  city: 'City',
  province: 'Province',
  country: 'US',
  zipCode: 'Zip Code',
  phone: 'Phone',
  phoneI: 'Int. Phone No.',
  email: 'Email',
  benefitType: 'Benefit Type',
  optIn: 'Opt In',
  issues: 'Issues',
  federalRecords: 'Federal Records',
  noticeAcknowledgement: 'Notice Acknowledgement',
  dic: 'DIC',
  veteranDateSigned: 'Veteran Date Signed',
  vaAuthorizedRepresentative: 'VA Authorized Representative',
  veteranDateSignedAS: 'Alternate Signer Date Signed',
  alternateSignerName: 'Alternate Signer Name',
  signature: 'Add Signature on your Profile',
};

export const HigherLevelReviewFileMap = {
  firstName: 'First Name',
  lastName: 'Last Name',
  ssn: 'SSN (Social Security Number)',
  currentVa: 'VA File Number',
  birthday: 'Birthday',
  serviceNumber: 'Service Number',
  insuranceNumber: 'Insurance Number',
  street: 'Street',
  unitNumber: 'Unit Number',
  city: 'City',
  province: 'Province',
  country: 'Country',
  zipCode: 'Zip Code',
  phone: 'Phone',
  phoneI: 'Int. Phone No.',
  email: 'Email',
  homeless: 'Homelessness',
  vet: 'Is Veteran?',
  //   section II
  claimantsName: 'Claimants Name',
  claimantsLastName: 'Claimants Last Name',
  claimantsSsn: 'Claimants SSN',
  claimantBirthday: 'Claimants Birthday',
  claimantsStreet: 'Claimants Street',
  claimantsUnitNumber: 'Claimants Unit Number',
  claimantsCity: 'Claimants City',
  claimantsProvince: 'Claimants Province',
  claimantsCountry: 'Claimants Country',
  claimantsZipCode: 'Claimants Zip Code',
  claimantsPhone: 'Claimants Phone',
  claimantsPhoneI: 'Claimants Int. Phone No',
  claimantsEmail: 'Claimants Email',

  // section III
  benefitType: 'Benefit Type',
  isInformalConference: 'Is Informal Conference',
  informalConferenceContact: 'Informal Conference Contact',
  //   section IV
  rName: 'Reference Name',
  rLastName: 'Representative Last Name',
  rPhone: 'Representative Phone No.',
  rEmail: 'Representative Email',
  issues: 'Issues',
  dateSigned: 'Date Signed',
  veteranDateSigned: 'Date Signed (Veteran)',
  veteranFirstName: 'First Name of VA Representative',
  veteranLastName: 'Last Name of VA Representative',
  signature: 'Add Signature on your Profile'
};

export const BoardAppealFileMap = {
  name: 'Name',
  fileNumber: 'File Number',
  birthday: 'Birthday',
  street: 'Street',
  homelessness: 'Homelessness',
  phone: 'Phone',
  email: 'Email',
  rName: 'Representatives Name',
  lawJudge: 'Law Judge',
  issueDecided: 'Issues Detected',
  issues: 'Issues',
  additionalIssue: 'Additional Issue',
  dateSigned: 'Date Signed',
  notVetName: 'Not Veteran Name',
  notVetBirthday: 'Not Veteran Birthday',
  hearingType: 'Hearing Type',
  signature: 'Add Signature on your Profile',
};

export const SupportOfClaimFileMap = {
  firstName: 'First Name',
  lastName: 'Last Name',
  ssn: 'SSN (Social Security Number)',
  currentVa: 'VA File Number',
  birthday: 'Birthday',
  serviceNumber: 'Service Number',
  street: 'Street',
  unitNumber: 'Unit Number',
  city: 'City',
  province: 'Province',
  country: 'US',
  zipCode: 'Zip Code',
  phone: 'Phone',
  phoneI: 'Int. Phone No.',
  email: 'Email',
  claimBenefits: 'Remarks',
  veteranDateSigned: 'Veteran Date Signed',
  hasSignature: 'Add Signature on your Profile',
  signature: 'Add Signature on your Profile',
};

export const PTSDStressorFileMap = {
  firstName: 'Veteran First Name',
  lastName: 'Veteran Last Name',
  ssn: 'Veteran SSN',
  currentVa: 'Veteran VA File Number', // optional
  birthday: 'Veteran Birthday',
  serviceNumber: 'Veteran Service Number', // optional

  phone: 'Veteran Phone Number',
  phoneI: '',
  email: '',

  // section II
  incidentDate1: 'Incident Date(1)',
  dateOfAssignmentFrom1: 'Date of Assignment From(1)',
  dateOfAssignmentTo1: 'Date of Assignment To(1)',
  incidentLocation1: 'Incident Location(1)',
  unitAssignmentDuringIncident0: 'Unit Assignment During Incident(0)',
  descriptionOfIncident1: 'Description of Incident(1)',
  medalReceived1: 'Medal Received(1)',

  person1FirstName: 'Person (1) First Name',
  person1LastName: 'Person (1) Last Name',
  person1Rank: 'Person (1) Rank', // optional
  injuryDate1: 'Injury Date(1)',
  checkOptions1: 'Check Options(1)', 
  checkOptionsOther1: 'Check Options Other(1)', 
  unitAssignmentDuringIncident1: 'Unit Assignment During Incident(1)',

  person2FirstName: 'Person (2) First Name  ',
  person2LastName: 'Person (2) Last Name',
  person2Rank: 'Person (2) Rank', // optional
  injuryDate2: 'Injury Date(2)',
  checkOptions2: 'Check Options(2)', 
  checkOptionsOther2: 'Check Options Other(2)', 
  unitAssignmentDuringIncident2: 'Unit Assignment During Incident(2)',



  incidentDate2: 'Incident Date(2)', // optional
  dateOfAssignmentFrom2: 'Date of Assignment From(2)', // optional
  dateOfAssignmentTo2: 'Date of Assignment To(2)', // optional
  incidentLocation2: 'Incident Location(2)', // optional
  unitAssignmentDuringIncident3: 'Unit Assignment During Incident(3)', // optional
  descriptionOfIncident2: 'Description of Incident(2)', // optional
  medalReceived2: 'Medal Received(2)', // optional


  person3FirstName: 'Person (3) First Name', // optional
  person3LastName: 'Person (3) Last Name', // optional
  person3Rank: 'Person (3) Rank', // optional
  injuryDate3: 'Injury Date(3)', // optional
  checkOptions3: 'Check Options(3)', // optional
  checkOptionsOther3: 'Check Options Other(3)', // optional
  unitAssignmentDuringIncident4: 'Unit Assignment During Incident(4)', // optional
  

  person4FirstName: 'Person (4) First Name', // optional
  person4LastName: 'Person (4) Last Name',
  person4Rank: 'Person (4) Rank', // optional
  injuryDate4: 'Injury Date(4)',  
  checkOptions4: 'Check Options(4)', 
  checkOptionsOther4: 'Check Options Other(4)', 
  unitAssignmentDuringIncident5: 'Unit Assignment During Incident(5)',

  remarks: 'Remarks', // optional
  hasSignature: 'Add Signature on your Profile',
  signature: 'Add Signature on your Profile',
  dateSigned: 'Date Signed',
};