export const StateData = [
  {
    name: 'Alabama',
    abbreviation: 'AL',
    selected: false,
  },
  {
    name: 'Alaska',
    abbreviation: 'AK',
    selected: false,
  },
  {
    name: 'American Samoa',
    abbreviation: 'AS',
    selected: false,
  },
  {
    name: 'Arizona',
    abbreviation: 'AZ',
    selected: false,
  },
  {
    name: 'Arkansas',
    abbreviation: 'AR',
    selected: false,
  },
  {
    name: 'California',
    abbreviation: 'CA',
    selected: false,
  },
  {
    name: 'Colorado',
    abbreviation: 'CO',
    selected: false,
  },
  {
    name: 'Connecticut',
    abbreviation: 'CT',
    selected: false,
  },
  {
    name: 'Delaware',
    abbreviation: 'DE',
    selected: false,
  },
  {
    name: 'District Of Columbia',
    abbreviation: 'DC',
    selected: false,
  },
  {
    name: 'Federated States Of Micronesia',
    abbreviation: 'FM',
    selected: false,
  },
  {
    name: 'Florida',
    abbreviation: 'FL',
    selected: false,
  },
  {
    name: 'Georgia',
    abbreviation: 'GA',
    selected: false,
  },
  {
    name: 'Guam',
    abbreviation: 'GU',
    selected: false,
  },
  {
    name: 'Hawaii',
    abbreviation: 'HI',
    selected: false,
  },
  {
    name: 'Idaho',
    abbreviation: 'ID',
    selected: false,
  },
  {
    name: 'Illinois',
    abbreviation: 'IL',
    selected: false,
  },
  {
    name: 'Indiana',
    abbreviation: 'IN',
    selected: false,
  },
  {
    name: 'Iowa',
    abbreviation: 'IA',
    selected: false,
  },
  {
    name: 'Kansas',
    abbreviation: 'KS',
    selected: false,
  },
  {
    name: 'Kentucky',
    abbreviation: 'KY',
    selected: false,
  },
  {
    name: 'Louisiana',
    abbreviation: 'LA',
    selected: false,
  },
  {
    name: 'Maine',
    abbreviation: 'ME',
    selected: false,
  },
  {
    name: 'Marshall Islands',
    abbreviation: 'MH',
    selected: false,
  },
  {
    name: 'Maryland',
    abbreviation: 'MD',
    selected: false,
  },
  {
    name: 'Massachusetts',
    abbreviation: 'MA',
    selected: false,
  },
  {
    name: 'Michigan',
    abbreviation: 'MI',
    selected: false,
  },
  {
    name: 'Minnesota',
    abbreviation: 'MN',
    selected: false,
  },
  {
    name: 'Mississippi',
    abbreviation: 'MS',
    selected: false,
  },
  {
    name: 'Missouri',
    abbreviation: 'MO',
    selected: false,
  },
  {
    name: 'Montana',
    abbreviation: 'MT',
    selected: false,
  },
  {
    name: 'Nebraska',
    abbreviation: 'NE',
    selected: false,
  },
  {
    name: 'Nevada',
    abbreviation: 'NV',
    selected: false,
  },
  {
    name: 'New Hampshire',
    abbreviation: 'NH',
    selected: false,
  },
  {
    name: 'New Jersey',
    abbreviation: 'NJ',
    selected: false,
  },
  {
    name: 'New Mexico',
    abbreviation: 'NM',
    selected: false,
  },
  {
    name: 'New York',
    abbreviation: 'NY',
    selected: false,
  },
  {
    name: 'North Carolina',
    abbreviation: 'NC',
    selected: false,
  },
  {
    name: 'North Dakota',
    abbreviation: 'ND',
    selected: false,
  },
  {
    name: 'Northern Mariana Islands',
    abbreviation: 'MP',
    selected: false,
  },
  {
    name: 'Ohio',
    abbreviation: 'OH',
    selected: false,
  },
  {
    name: 'Oklahoma',
    abbreviation: 'OK',
    selected: false,
  },
  {
    name: 'Oregon',
    abbreviation: 'OR',
    selected: false,
  },
  {
    name: 'Palau',
    abbreviation: 'PW',
    selected: false,
  },
  {
    name: 'Pennsylvania',
    abbreviation: 'PA',
    selected: false,
  },
  {
    name: 'Puerto Rico',
    abbreviation: 'PR',
    selected: false,
  },
  {
    name: 'Rhode Island',
    abbreviation: 'RI',
    selected: false,
  },
  {
    name: 'South Carolina',
    abbreviation: 'SC',
    selected: false,
  },
  {
    name: 'South Dakota',
    abbreviation: 'SD',
    selected: false,
  },
  {
    name: 'Tennessee',
    abbreviation: 'TN',
    selected: false,
  },
  {
    name: 'Texas',
    abbreviation: 'TX',
    selected: false,
  },
  {
    name: 'Utah',
    abbreviation: 'UT',
    selected: false,
  },
  {
    name: 'Vermont',
    abbreviation: 'VT',
    selected: false,
  },
  {
    name: 'Virgin Islands',
    abbreviation: 'VI',
    selected: false,
  },
  {
    name: 'Virginia',
    abbreviation: 'VA',
    selected: false,
  },
  {
    name: 'Washington',
    abbreviation: 'WA',
    selected: false,
  },
  {
    name: 'West Virginia',
    abbreviation: 'WV',
    selected: false,
  },
  {
    name: 'Wisconsin',
    abbreviation: 'WI',
    selected: false,
  },
  {
    name: 'Wyoming',
    abbreviation: 'WY',
    selected: false,
  },
];

export const branchOfServiceData = [
  'Army',
  'Navy',
  'Marine Corps',
  'Air Force',
  'Coast Guard',
  'Space Force',
  'NOAA',
  'USPHA',
];

export const menuData = [
  {
    id: 'request_cfile',
    title: 'Request C-file/DD 214',
    status: true,
    submenu: [
      {
        id: 'req_cfile_1',
        title: 'Request C-File/DD 214 (Form 20-10206)',
        path: '/forms/request-c-file',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'misc_forms',
    title: 'Sworn Statements and Misc Forms',
    status: true,
    submenu: [
      {
        id: 'misc_1',
        title: 'PTSD Stressor Statement (Form 21-0781)',
        path: '/forms/ptsd-stressor',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'misc_2',
        title: 'Statement in Support of Claim (Form 21-4138)',
        path: '/forms/support-claim',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'misc_3',
        title: 'Medical Records Release (Form 21-4142)',
        path: '/forms/medical-records',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'misc_3',
        title: 'Increased Rating due to TDIU (Unemployability) (Form 21-8940)',
        path: '/forms/tdiu',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'file_appeal',
    title: 'File An Appeal',
    status: true,
    submenu: [
      {
        id: 'appeal_1',
        title: 'Higher Level Review (Form 20-0996)',
        path: '/forms/higher-level-review',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'appeal_2',
        title: 'Board Appeal (Form 20-0995)',
        path: '/forms/board-appeal',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'appeal_3',
        title: 'Supplemental Claim Appeal',
        path: '/forms/supplemental-claim',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'court_appeal',
    title: 'Court of Appeals for Veterans Claims-File Appeal',
    status: true,
    submenu: [
      {
        id: 'court_1',
        title: 'Notice of Appeal (NOA) & Optional Fee Waiver',
        path: '/forms/noa',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'court_2',
        title: 'Declaration of Financial Hardship (Fee Waiver)',
        path: '/forms/fee-waiver',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'submit_claim',
    title: 'Submit a Claim',
    status: true,
    submenu: [
      {
        id: 'claim_1',
        title: 'New Claim or Increase (Form 21-526EZ)',
        path: '/forms/new-claim',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'claim_2',
        title: 'Supplemental Claim & Reopening (Form 20-0995)',
        path: '/forms/supplemnetal-claim-reopening',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
];

export const disabilityData = [
  '7335: Anorectal abscess.',
  '8020: Brain abscess.',
  '7501: Kidney abscess.',
  '7350: Liver abscess.',
  '6824: Lung abscess.',
  '7828: Acne.',
  '7908: Acromegaly.',
  '6822: Actinomycosis.',
  "7911: Addison's disease.",
  '7702: Agranulocytosis, acquired.',
  '7717: AL amyloidosis.',
  '7831: Alopecia areata.',
  '7321: Amebiasis.',
  '5120: Complete amputation, upper extremity.',
  '5121: Amputation above insertion of deltoid.',
  '5122: Amputation below insertion of deltoid.',
  '5126: Amputation of five digits of one hand.',
  '5127: Amputation of thumb, index, long and ring.',
  '5128: Amputation of thumb, index, long and little.',
  '5129: Amputation of thumb, index, ring and little.',
  '5130: Amputation of thumb, long, ring and little.',
  '5131: Amputation of index, long, ring and little.',
  '5132: Amputation of thumb, index and long.',
  '5133: Amputation of thumb, index and ring.',
  '5134: Amputation of thumb, index and little.',
  '5135: Amputation of thumb, long and ring.',
  '5136: Amputation of thumb, long and little.',
  '5137: Amputation of thumb, ring and little.',
  '5138: Amputation of index, long and ring.',
  '5139: Amputation of index, long and little.',
  '5140: Amputation of index, ring and little.',
  '5141: Amputation of long, ring and little.',
  '5142: Amputation of thumb and index.',
  '5143: Amputation of thumb and long.',
  '5144: Amputation of thumb and ring.',
  '5145: Amputation of thumb and little.',
  '5146: Amputation of index and long.',
  '5147: Amputation of index and ring.',
  '5148: Amputation of index and little.',
  '5149: Amputation of long and ring.',
  '5150: Amputation of long and little.',
  '5151: Amputation of ring and little.',
  '5152: Amputation of thumb.',
  '5153: Amputation of index finger.',
  '5154: Amputation of long finger.',
  '5155: Amputation of ring finger.',
  '5156: Amputation of little finger.',
  '5123: Amputation of forearm above insertion of pronator teres.',
  '5124: Amputation of forearm below insertion of pronator teres.',
  '5163: Amputation of leg with defective stump.',
  '5164: Amputation of leg not improvable by prosthesis controlled by natural knee action.',
  '5165: Amputation of leg at lower level, permitting prosthesis.',
  '5166: Amputation of forefoot, proximal to metatarsal bones.',
  '5170: Amputation of all toes, without metatarsal loss or transmetatarsal, with up to half of metatarsal loss.',
  '5171: Amputation of great toe.',
  '5172: Amputation of toe, other than great, with removal of metatarsal head.',
  '5173: Amputation of three or more toes, without metatarsal involvement.',
  '5160: Complete amputation, lower extremity.',
  '5161: Amputation of thigh, upper third.',
  '5162: Amputation of thigh, middle or lower thirds.',
  '8017: Amyotrophic lateral sclerosis.',
  '6061: Anatomical loss of both eyes.',
  '6063: Anatomical loss of one eye, with visual acuity of other eye 5/200 (1.5/60).',
  '6064: Anatomical loss of one eye, with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6065: Anatomical loss of one eye, with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6066: Anatomical loss of one eye, with visual acuity of other eye 20/40 (6/12).',
  '5107: Anatomical loss of both feet.',
  '5106: Anatomical loss of both hands.',
  '5108: Anatomical loss of one hand and one foot.',
  '5105: Anatomical loss of one foot and loss of use of one hand.',
  '5104: Anatomical loss of one hand and loss of use of one foot.',
  '7723: Acquired hemolytic anemia.',
  '7721: Folic acid deficiency.',
  '7720: Iron deficiency anemia.',
  '7722: Pernicious anemia and Vitamin B12 deficiency anemia.',
  '7110: Aortic aneurysm, ascending, thoracic, abdominal.',
  '7111: Aneurysm, large artery.',
  '7118: Aneurysm, small artery.',
  '5270: Ankylosis of ankle.',
  '5224: Ankylosis of thumb.',
  '5225: Ankylosis of index finger.',
  '5226: Ankylosis of long finger.',
  '5227: Ankylosis of ring or little finger.',
  '5205: Ankylosis of elbow.',
  '5220: Ankylosis of five digits of one hand, favorable.',
  '5221: Ankylosis of four digits of one hand, favorable.',
  '5222: Ankylosis of three digits of one hand, favorable.',
  '5223: Ankylosis of two digits of one hand, favorable.',
  '5216: Ankylosis of five digits of one hand, unfavorable.',
  '5217: Ankylosis of four digits of one hand, unfavorable.',
  '5218: Ankylosis of three digits of one hand, unfavorable.',
  '5219: Ankylosis of two digits of one hand, unfavorable.',
  '5250: Ankylosis of hip.',
  '5256: Ankylosis of knee.',
  '5200: Ankylosis of scapulohumeral articulation.',
  '5272: Ankylosis of subastragalar or tarsal joint.',
  '5214: Ankylosis of wrist.',
  '5240: Ankylosing spondylitis.',
  '6029: Aphakia.',
  '6519: Aphonia, organic.',
  '7716: Aplastic anemia.',
  '7005: Arteriosclerotic heart disease.',
  '7113: Arteriovenous fistula.',
  '5003: Arthritis, degenerative, other than post-traumatic.',
  '5004: Arthritis, gonorrheal.',
  '5009: Arthritis, other specified forms (excluding gout).',
  '5005: Arthritis, pneumococcic.',
  '5010: Arthritis, post-traumatic.',
  '5002: Arthritis, multi-joint (except post-traumatic and gout).',
  '5008: Arthritis, streptococcic.',
  '5007: Arthritis, syphilitic.',
  '5006: Arthritis, typhoid.',
  '5009: Arthropathy.',
  '6833: Asbestosis.',
  '6838: Aspergillosis.',
  '6602: Asthma, bronchial.',
  '5274: Astragalectomy.',
  '7534: Atherosclerotic renal disease.',
  '8107: Athetosis.',
  '7015: Atrioventricular block.',
  '6313: Avitaminosis.',
  '6306: Bartonellosis.',
  '6314: Beriberi.',
  '7515: Bladder, calculus in.',
  '7545: Bladder, diverticulum of.',
  '7516: Bladder, fistula in.',
  '7517: Bladder, injury of.',
  '7542: Bladder, neurogenic.',
  '6836: Blastomycosis.',
  '6062: Blindness, both eyes, only light perception.',
  '6067: Blindness, one eye, only light perception, with visual acuity of other eye 5/200 (1.5/60).',
  '6068: Blindness, one eye, only light perception, with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6069: Blindness, one eye, only light perception, with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6070: Blindness, one eye, only light perception, with visual acuity of other eye 20/40 (6/12).',
  '5015: Bones, neoplasm, benign.',
  '5012: Bones, neoplasm, malignant, primary or secondary.',
  '5275: Bones, shortening of the lower extremity.',
  '7009: Bradycardia (Bradyarrhythmia), symptomatic, requiring permanent pacemaker implantation.',
  '8020: Brain abscess.',
  '7631: Breast, benign neoplasms.',
  '7626: Breast surgery.',
  '6601: Bronchiectasis.',
  '6600: Bronchitis.',
  '6316: Brucellosis.',
  "7115: Buerger's disease.",
  '8005: Bulbar palsy.',
  '7815: Bullous disorders.',
  '5019: Bursitis.',
  '6330: Campylobacter jejuni infection.',
  '7018: Cardiac pacemakers, implantable.',
  '7019: Cardiac transplantation.',
  '7020: Cardiomyopathy.',
  '7919: C-cell hyperplasia, thyroid.',
  '6028: Cataract, senile and others.',
  '6027: Cataract, traumatic.',
  '8046: Cerebral arteriosclerosis.',
  '5237: Cervical strain.',
  '7612: Cervix disease or injury.',
  "8106: Chorea, Huntington's.",
  "8105: Chorea, Sydenham's.",
  '7829: Chloracne.',
  '7314: Cholangitis, chronic.',
  '7318: Cholecystectomy (gallbladder removal), complications of (such as strictures and biliary leaks).',
  '7314: Cholecystitis, chronic.',
  '7315: Cholelithiasis, chronic.',
  '6005: Choroiditis.',
  '6354: Chronic Fatigue Syndrome (CFS).',
  '6824: Chronic lung abscess.',
  '6604: Chronic obstructive pulmonary disease.',
  '6835: Coccidioidomycosis.',
  '7122: Cold injury residuals.',
  '7323: Colitis, ulcerative.',
  '5331: Compartment syndrome.',
  '7621: Complete or incomplete pelvic organ prolapse due to injury or disease or surgical complications of pregnancy, including uterine or vaginal vault prolapse, cystocele, urethrocele, rectocele, enterocele, or combination.',
  '6017: Conjunctivitis, trachomatous.',
  '6018: Conjunctivitis, other.',
  '7017: Coronary bypass surgery.',
  '6331: Coxiella burnetii infection (Q Fever).',
  '6837: Cryptococcosis.',
  "7907: Cushing's syndrome.",
  '7821: Cutaneous manifestations of collagen-vascular diseases not listed elsewhere.',
  '6004: Cyclitis.',
  '7512: Cystitis, chronic.',
  '6031: Dacryocystitis.',
  '5011: Decompression illness.',
  '7806: Dermatitis or eczema.',
  '7813: Dermatophytosis.',
  '5324: Diaphragm, rupture.',
  '6840: Diaphragm, paralysis or paresis.',
  '6090: Diplopia.',
  '6092: Diplopia, limited muscle function, eye.',
  "7911: Addison's disease.",
  "7115: Buerger's disease.",
  '7355: Celiac disease.',
  "7326: Crohn's disease.",
  '7314: Gallbladder and biliary tract, chronic.',
  "7709: Hodgkin's disease.",
  "6302: Leprosy (Hansen's Disease).",
  '6319: Lyme disease.',
  "5279: Morton's disease.",
  '6320: Parasitic disease.',
  '7800: Disfigurement of head, face or neck.',
  '5258: Dislocated cartilage, semilunar.',
  '6033: Dislocated lens, crystalline.',
  '7540: Disseminated intravascular coagulation.',
  '7324: Distomiasis, intestinal or hepatic.',
  '7322: Dysentery, bacillary.',
  '6020: Ectropion.',
  '8007: Embolism, brain.',
  '6603: Emphysema, pulmonary.',
  '8000: Encephalitis, epidemic, chronic.',
  '7001: Endocarditis.',
  '7629: Endometriosis.',
  '7325: Enteritis, chronic.',
  '7326: Enterocolitis, chronic.',
  '6021: Entropion.',
  '6828: Eosinophilic granuloma of lung.',
  '8913: Epilepsy, diencephalic.',
  '8910: Epilepsy, grand mal.',
  '8912: Epilepsy, Jacksonian and focal motor or sensory.',
  '8911: Epilepsy, petit mal.',
  '8914: Epilepsy, psychomotor.',
  '6025: Epiphora.',
  '7827: Erythema multiforme.',
  '7817: Erythroderma.',
  '7119: Erythromelalgia.',
  "7207: Barrett's esophagus.",
  '7205: Esophagus, diverticulum.',
  '7204: Esophagus, motility disorder.',
  '7203: Esophagus, stricture.',
  '7614: Fallopian tube.',
  '7632: Female sexual arousal disorder (FSAD).',
  '6308: Relapsing fever.',
  '6309: Rheumatic fever.',
  '6825: Fibrosis of lung, diffuse interstitial.',
  '5025: Fibromyalgia.',
  '7335: Fistula in ano.',
  '7624: Fistula, rectovaginal.',
  '7625: Fistula, urethrovaginal.',
  '5276: Flatfoot, acquired.',
  '7307: Gastritis, chronic.',
  '7206: Gastroesophageal reflux disease.',
  '5263: Genu recurvatum.',
  '6012: Glaucoma, congestive or inflammatory.',
  '6013: Glaucoma, simple, primary, noncongestive.',
  '7536: Glomerulonephritis.',
  '5017: Gout.',
  "7900: Graves' disease.",
  '5281: Hallux rigidus.',
  '5280: Hallux valgus.',
  '5282: Hammer toe.',
  '7016: Heart valve replacement.',
  '7718: Essential thrombocythemia and primary myelofibrosis.',
  '7705: Immune thrombocytopenia.',
  '7712: Multiple myeloma.',
  '7725: Myelodysplastic syndromes.',
  '7724: Solitary plasmacytoma.',
  '8012: Hematomyelia.',
  '6007: Hemorrhage, intra-ocular.',
  '6329: Hemorrhagic fevers, including dengue, yellow fever, and others.',
  '7336: Hemorrhoids.',
  '7354: Hepatitis C.',
  '7338: Hernia, femoral, inguinal, umbilical, ventral, incisional, and other.',
  '7346: Hernia, hiatal and paraesophageal.',
  '5326: Hernia, muscle.',
  '5023: Heterotopic ossification.',
  '5254: Hip, flail joint.',
  '6351: HIV-Related Illness.',
  "7709: Hodgkin's lymphoma.",
  '7509: Hydronephrosis.',
  '7917: Hyperaldosteronism.',
  '7832: Hyperhidrosis.',
  '7904: Hyperparathyroidism.',
  '7916: Hyperpituitarism.',
  '7007: Hypertensive heart disease.',
  '7101: Hypertensive vascular disease.',
  '7008: Hyperthyroid heart disease.',
  '7900: Hyperthyroidism.',
  '7905: Hypoparathyroidism.',
  '7903: Hypothyroidism.',
  '5202: Impairment of humerus.',
  '5203: Impairment of clavicle or scapula.',
  '5209: Impairment of elbow.',
  '5253: Impairment of thigh.',
  '5255: Impairment of femur.',
  '5257: Impairment of knee, other.',
  '6080: Impairment of field vision.',
  '5262: Impairment of tibia and fibula.',
  '7332: Impairment of rectum and anus.',
  '5211: Impairment of ulna.',
  '7018: Implantable cardiac pacemakers.',
  '7820: Infections of the skin.',
  '7517: Injury of bladder.',
  '7631: Injury of breast.',
  '6009: Injury of eye, unhealed.',
  '5284: Injury of foot.',
  '7317: Injury of gallbladder.',
  '7201: Injury of lips.',
  '7311: Injury of liver, residuals.',
  '7200: Injury of mouth, soft tissue.',
  '5301: Muscle injury, Group I Function: Upward rotation of scapula.',
  '5302: Muscle injury, Group II Function: Depression of arm.',
  '5303: Muscle injury, Group III Function: Elevation and abduction of arm.',
  '5304: Muscle injury, Group IV Function: Stabilization of shoulder.',
  '5305: Muscle injury, Group V Function: Elbow supination.',
  '5306: Muscle injury, Group VI Function: Extension of elbow.',
  '5307: Muscle injury, Group VII Function: Flexion of wrist and fingers.',
  '5308: Muscle injury, Group VIII Function: Extension of wrist, fingers, thumb.',
  '5309: Muscle injury, Group IX Function: Forearm muscles.',
  '5310: Muscle injury, Group X Function: Movement of forefoot and toes.',
  '5311: Muscle injury, Group XI Function: Propulsion of foot.',
  '5312: Muscle injury, Group XII Function: Dorsiflexion.',
  '5313: Muscle injury, Group XIII Function: Extension of hip and flexion of knee.',
  '5314: Muscle injury, Group XIV Function: Extension of knee.',
  '5315: Muscle injury, Group XV Function: Adduction of hip.',
  '5316: Muscle injury, Group XVI Function: Flexion of hip.',
  '5317: Muscle injury, Group XVII Function: Extension of hip.',
  '5318: Muscle injury, Group XVIII Function: Outward rotation of thigh.',
  '5319: Muscle injury, Group XIX Function: Abdominal wall and lower thorax.',
  '5320: Muscle injury, Group XX Function: Postural support of body.',
  '5321: Muscle injury, Group XXI Function: Respiration.',
  '5322: Muscle injury, Group XXII Function: Rotary and forward movements, head.',
  '5323: Muscle injury, Group XXIII Function: Movements of head.',
  '6521: Injury of pharynx.',
  '5236: Injury of sacroiliac.',
  '6841: Injury of spinal cord.',
  '7310: Injury of stomach, residuals.',
  '6003: Iritis.',
  '7537: Interstitial nephritis, including gouty nephropathy, disorders of calcium metabolism.',
  '5243: Intervertebral disc syndrome.',
  '7330: Intestine, fistulous disease, external.',
  '7329: Intestine, large, resection of.',
  '7328: Intestine, small, resection of.',
  '7319: Irritable bowel syndrome (IBS).',
  '7824: Keratinization, diseases of.',
  '6001: Keratitis.',
  '6035: Keratoconus.',
  '7501: Kidney abscess.',
  '7533: Kidney, cystic diseases.',
  '7500: Kidney, removal.',
  '7531: Kidney transplant.',
  '7505: Kidney, tuberculosis.',
  '6842: Kyphoscoliosis, pectus excavatum/carinatum.',
  '6022: Lagophthalmos.',
  '6518: Laryngectomy.',
  '6515: Laryngitis, tuberculous.',
  '6516: Laryngitis, chronic.',
  '6520: Larynx, stenosis of.',
  '7807: Leishmaniasis, American (New World).',
  '7808: Leishmaniasis, Old World.',
  "6302: Leprosy (Hansen's Disease).",
  '7703: Leukemia.',
  '7719: Chronic myelogenous leukemia (CML).',
  '5207: Limitation of extension, forearm.',
  '5261: Limitation of extension, leg.',
  '5212: Limitation of extension, radius.',
  '5213: Limitation of supination and pronation.',
  '5251: Limitation of extension, thigh.',
  '5208: Limitation of extension and flexion, forearm.',
  '5206: Limitation of flexion, forearm.',
  '5260: Limitation of flexion, leg.',
  '5252: Limitation of flexion, thigh.',
  '5271: Limitation of motion, ankle.',
  '5201: Limitation of motion, arm.',
  '5229: Limitation of motion, index or long finger.',
  '5230: Limitation of motion, ring or little finger.',
  '9905: Limitation of motion, temporomandibular.',
  '5228: Limitation of motion, thumb.',
  '5215: Limitation of motion, wrist.',
  '7345: Liver disease, chronic, without cirrhosis.',
  '7351: Liver transplant.',
  '7312: Liver, cirrhosis.',
  '6207: Loss of auricle.',
  '9908: Loss of condyloid process.',
  '9909: Loss of coronoid process.',
  '6023: Loss of eyebrows.',
  '6024: Loss of eyelashes.',
  '6032: Loss of eyelids.',
  '9911: Loss of palate, hard.',
  '9902: Loss of mandible, including ramus, unilaterally or bilaterally.',
  '9914: Loss of maxilla, more than half.',
  '9915: Loss of maxilla, less than half.',
  '6504: Loss of nose, part of, or scars.',
  '5296: Loss of skull, part of.',
  '6275: Loss of smell, sense of.',
  '6276: Loss of taste, sense of.',
  '9913: Loss of teeth.',
  '7202: Loss of tongue, whole or part.',
  '5110: Loss of use of both feet.',
  '5109: Loss of use of both hands.',
  '5167: Loss of use of foot.',
  '5125: Loss of use of hand.',
  '5111: Loss of use of one hand and one foot.',
  '5237: Lumbosacral strain.',
  '6350: Lupus erythematosus.',
  '7809: Lupus erythematosus, discoid.',
  '6319: Lyme disease.',
  '6304: Malaria.',
  '7833: Malignant melanoma.',
  '9904: Malunion of mandible.',
  '5273: Malunion of os calcis or astragalus.',
  '9916: Malunion or nonunion of maxilla.',
  '9900: Maxilla or mandible, chronic osteomyelitis, osteonecrosis, or osteoradionecrosis of.',
  '6318: Melioidosis.',
  "6205: Meniere's syndrome.",
  '8019: Meningitis, cerebrospinal, epidemic.',
  '9520: Anorexia nervosa.',
  '9432: Bipolar disorder.',
  '9521: Bulimia nervosa.',
  '9440: Chronic adjustment disorder.',
  '9424: Conversion disorder (functional neurological symptom disorder).',
  '9431: Cyclothymic disorder.',
  '9300: Delirium.',
  '9208: Delusional disorder.',
  '9417: Depersonalization/derealization disorder.',
  '9416: Dissociative amnesia; dissociative identity disorder.',
  '9400: Generalized anxiety disorder.',
  '9425: Illness anxiety disorder.',
  '9434: Major depressive disorder.',
  "9312: Major or mild neurocognitive disorder due to Alzheimer's disease.",
  '9326: Major or mild neurocognitive disorder due to another medical condition or substance/medication-induced.',
  '9301: Major or mild neurocognitive disorder due to HIV or other infections.',
  '9304: Major or mild neurocognitive disorder due to traumatic brain injury.',
  '9305: Major or mild vascular neurocognitive disorder.',
  '9404: Obsessive compulsive disorder.',
  '9210: Other specified and unspecified schizophrenia spectrum and other psychotic disorders.',
  '9410: Other specified anxiety disorder.',
  '9422: Other specified somatic symptom and related disorder.',
  '9412: Panic disorder and/or agoraphobia.',
  '9433: Persistent depressive disorder (dysthymia).',
  '9411: Posttraumatic stress disorder.',
  '9211: Schizoaffective disorder.',
  '9201: Schizophrenia.',
  '9421: Somatic symptom disorder.',
  '9403: Specific phobia; social anxiety disorder (social phobia).',
  '9423: Unspecified somatic symptom and related disorder.',
  '9413: Unspecified anxiety disorder.',
  '9435: Unspecified depressive disorder.',
  '9310: Unspecified neurocognitive disorder.',
  '5279: Metatarsalgia.',
  '8100: Migraine.',
  '6839: Mucormycosis.',
  '8018: Multiple sclerosis.',
  '8010: Myelitis.',
  '7006: Myocardial infarction.',
  '5021: Myositis.',
  '8108: Narcolepsy.',
  '7631: Neoplasms, benign, breast.',
  '7344: Neoplasms, benign, digestive system.',
  '6209: Neoplasms, benign, ear.',
  '7915: Neoplasms, benign, endocrine.',
  '7529: Neoplasms, benign, genitourinary.',
  '7628: Neoplasms, benign, gynecological.',
  '9917: Neoplasms, benign, hard and soft tissue.',
  '5328: Neoplasms, benign, muscle.',
  '6820: Neoplasms, benign, respiratory.',
  '7819: Neoplasms, benign, skin.',
  '7630: Neoplasms, malignant, breast.',
  '7343: Neoplasms, malignant, digestive system.',
  '6208: Neoplasms, malignant, ear.',
  '7914: Neoplasms, malignant, endocrine.',
  '7528: Neoplasms, malignant, genitourinary.',
  '7627: Neoplasms, malignant, gynecological.',
  '9918: Neoplasms, malignant, hard and soft tissue.',
  '5327: Neoplasms, malignant, muscle.',
  '6819: Neoplasms, malignant, respiratory.',
  '7818: Neoplasms, malignant, skin.',
  '7502: Nephritis, chronic.',
  '7508: Nephrolithiasis/Ureterolithiasis/Nephrocalcinosis.',
  '7507: Nephrosclerosis, arteriolar.',
  '8405: Neuralgia, fifth (trigeminal) cranial nerve.',
  '8407: Neuralgia, seventh (facial) cranial nerve.',
  '8409: Neuralgia, ninth (glossopharyngeal) cranial nerve.',
  '8410: Neuralgia, tenth (pneumogastric, vagus) cranial nerve.',
  '8411: Neuralgia, eleventh (spinal accessory, external branch) cranial nerve.',
  '8412: Neuralgia, twelfth (hypoglossal) cranial nerve.',
  '8710: Neuralgia, upper radicular group, peripheral nerve.',
  '8711: Neuralgia, middle radicular group, peripheral nerve.',
  '8712: Neuralgia, lower radicular group, peripheral nerve.',
  '8713: Neuralgia, all radicular groups, peripheral nerve.',
  '8714: Neuralgia, musculospiral (radial), peripheral nerve.',
  '8715: Neuralgia, median, peripheral nerve.',
  '8716: Neuralgia, ulnar, peripheral nerve.',
  '8717: Neuralgia, musculocutaneous, peripheral nerve.',
  '8718: Neuralgia, circumflex, peripheral nerve.',
  '8719: Neuralgia, long thoracic, peripheral nerve.',
  '8720: Neuralgia, sciatic, peripheral nerve.',
  '8721: Neuralgia, external popliteal (common peroneal), peripheral nerve.',
  '8722: Neuralgia, musculocutaneous (superficial peroneal), peripheral nerve.',
  '8723: Neuralgia, anterior tibial (deep peroneal), peripheral nerve.',
  '8724: Neuralgia, internal popliteal (tibial), peripheral nerve.',
  '8725: Neuralgia, posterior tibial, peripheral nerve.',
  '8726: Neuralgia, anterior crural (femoral), peripheral nerve.',
  '8727: Neuralgia, internal saphenous, peripheral nerve.',
  '8728: Neuralgia, obturator, peripheral nerve.',
  '8729: Neuralgia, external cutaneous nerve of thigh, peripheral nerve.',
  '8730: Neuralgia, ilio-inguinal, peripheral nerve.',
  '6026: Neuritis, optic.',
  '8610: Neuritis, upper radicular group, peripheral nerve.',
  '8611: Neuritis, middle radicular group, peripheral nerve.',
  '8612: Neuritis, lower radicular group, peripheral nerve.',
  '8613: Neuritis, all radicular groups, peripheral nerve.',
  '8614: Neuritis, musculospiral (radial), peripheral nerve.',
  '8615: Neuritis, median, peripheral nerve.',
  '8616: Neuritis, ulnar, peripheral nerve.',
  '8617: Neuritis, musculocutaneous, peripheral nerve.',
  '8618: Neuritis, circumflex, peripheral nerve.',
  '8619: Neuritis, long thoracic, peripheral nerve.',
  '8620: Neuritis, sciatic, peripheral nerve.',
  '8621: Neuritis, external popliteal (common peroneal), peripheral nerve.',
  '8622: Neuritis, musculocutaneous (superficial peroneal), peripheral nerve.',
  '8623: Neuritis, anterior tibial (deep peroneal), peripheral nerve.',
  '8624: Neuritis, internal popliteal (tibial), peripheral nerve.',
  '8625: Neuritis, posterior tibial, peripheral nerve.',
  '8626: Neuritis, anterior crural (femoral), peripheral nerve.',
  '8627: Neuritis, internal saphenous, peripheral nerve.',
  '8628: Neuritis, obturator, peripheral nerve.',
  '8629: Neuritis, external cutaneous nerve of thigh, peripheral nerve.',
  '8630: Neuritis, ilio-inguinal, peripheral nerve.',
  '7542: Neurogenic bladder.',
  '5015: New growths, benign, bones.',
  '8003: New growths, benign, brain.',
  '6015: New growths, benign, eye, orbit, and adnexa.',
  '8022: New growths, benign, spinal cord.',
  '5012: New growths, malignant, bones.',
  '8002: New growths, malignant, brain.',
  '6014: New growths, malignant, eye, orbit, and adnexa.',
  '8021: New growths, malignant, spinal cord.',
  '6823: Nocardiosis.',
  "7715: Non-Hodgkin's lymphoma.",
  '6312: Nontuberculosis mycobacterium infection.',
  '6333: Nontyphoid salmonella infection.',
  '9903: Nonunion of mandible, confirmed by diagnostic imaging studies.',
  '5210: Nonunion of radius and ulna.',
  '6016: Nystagmus, central.',
  '5016: Osteitis deformans.',
  '5014: Osteomalacia, residuals of.',
  '5000: Osteomyelitis.',
  '5013: Osteoporosis, residuals of.',
  '6210: Otitis media, externa.',
  '6201: Otitis media, nonsuppurative.',
  '6200: Otitis media, suppurative.',
  '6202: Otosclerosis.',
  '7620: Ovaries, atrophy of both.',
  '7615: Ovary, disease or injury.',
  '7619: Ovary, removal.',
  '8005: Palsy, bulbar.',
  '7347: Pancreas, chronic pancreatitis.',
  '7357: Pancreas, post pancreatectomy syndrome.',
  '7303: Pancreas, surgery, complications of.',
  '7352: Pancreas, transplant.',
  '7538: Papillary necrosis.',
  '7822: Papulosquamous disorders.',
  '6030: Paralysis, accommodation.',
  '8004: Paralysis agitans.',
  '5244: Paralysis, complete, traumatic.',
  '8205: Paralysis, fifth (trigeminal) cranial nerve.',
  '8207: Paralysis, seventh (facial) cranial nerve.',
  '8209: Paralysis, ninth (glossopharyngeal) cranial nerve.',
  '8210: Paralysis, tenth (pneumogastric, vagus) cranial nerve.',
  '8211: Paralysis, eleventh (spinal accessory, external branch) cranial nerve.',
  '8212: Paralysis, twelfth (hypoglossal) cranial nerve.',
  '8510: Paralysis, upper radicular group, peripheral nerve.',
  '8511: Paralysis, middle radicular group, peripheral nerve.',
  '8512: Paralysis, lower radicular group, peripheral nerve.',
  '8513: Paralysis, all radicular groups, peripheral nerve.',
  '8514: Paralysis, musculospiral (radial), peripheral nerve.',
  '8515: Paralysis, median, peripheral nerve.',
  '8516: Paralysis, ulnar, peripheral nerve.',
  '8517: Paralysis, musculocutaneous, peripheral nerve.',
  '8518: Paralysis, circumflex, peripheral nerve.',
  '8519: Paralysis, long thoracic, peripheral nerve.',
  '8520: Paralysis, sciatic, peripheral nerve.',
  '8521: Paralysis, external popliteal (common peroneal), peripheral nerve.',
  '8522: Paralysis, musculocutaneous (superficial peroneal), peripheral nerve.',
  '8523: Paralysis, anterior tibial nerve (deep peroneal), peripheral nerve.',
  '8524: Paralysis, internal popliteal (tibial), peripheral nerve.',
  '8525: Paralysis, posterior tibial nerve, peripheral nerve.',
  '8526: Paralysis, anterior crural nerve (femoral), peripheral nerve.',
  '8527: Paralysis, internal saphenous, peripheral nerve.',
  '8528: Paralysis, obturator, peripheral nerve.',
  '8529: Paralysis, external cutaneous nerve of thigh, peripheral nerve.',
  '8530: Paralysis, ilio-inguinal, peripheral nerve.',
  '8104: Paramyoclonus multiplex.',
  '6320: Parasitic disease.',
  '6315: Pellagra.',
  '7522: Penis, erectile dysfunction.',
  '7521: Penis, removal of glans.',
  '7520: Penis, removal of half or more.',
  '7003: Pericardial adhesions.',
  '7002: Pericarditis.',
  '7114: Peripheral arterial disease.',
  '6204: Peripheral vestibular disorders.',
  '7301: Peritoneum, adhesions.',
  '7331: Peritonitis.',
  '5278: Pes cavus (Claw foot), acquired.',
  '7918: Pheochromocytoma.',
  '6307: Plague.',
  '5269: Plantar fasciitis.',
  '6845: Pleural effusion or fibrosis.',
  '7912: Pluriglandular syndrome.',
  '6832: Pneumoconiosis.',
  '6829: Pneumonitis & fibrosis, drug-induced.',
  '6830: Pneumonitis & fibrosis, radiation-induced.',
  '8011: Poliomyelitis, anterior.',
  '7704: Polycythemia vera.',
  '7912: Polyglandular syndrome.',
  '6046: Post-chiasmal disorders.',
  '7308: Postgastrectomy syndromes.',
  '7121: Post-phlebitic syndrome.',
  '6844: Post-surgical residual.',
  '8023: Progressive muscular atrophy.',
  '7527: Prostate gland injuries, infections, hypertrophy, postoperative residuals, bladder outlet obstruction.',
  '7525: Prostatitis, urethritis, epididymitis, orchitis (unilateral or bilateral), chronic only.',
  '5056: Prosthetic implants, ankle replacement.',
  '5052: Prosthetic implants, elbow replacement.',
  '5054: Prosthetic implants, hip, resurfacing or replacement.',
  '5055: Prosthetic implants, knee, resurfacing or replacement.',
  '5051: Prosthetic implants, shoulder replacement.',
  '5053: Prosthetic implants, wrist replacement.',
  '7816: Psoriasis.',
  '6034: Pterygium.',
  '6019: Ptosis.',
  '6817: Pulmonary vascular disease.',
  '7337: Pruritus ani (anal itching).',
  '7504: Pyelonephritis, chronic.',
  "7124: Raynaud's disease (primary Raynaud's).",
  "7117: Raynaud's syndrome (secondary Raynaud's phenomenon, secondary Raynaud's).",
  '7333: Rectum & anus, stricture.',
  '7334: Rectum, prolapse.',
  '5259: Removal of cartilage, semilunar.',
  '5298: Removal of coccyx.',
  '7318: Removal of gall bladder.',
  '7500: Removal of kidney.',
  '7521: Removal of penis glans.',
  '7520: Removal of penis half or more.',
  '5297: Removal of ribs.',
  '7524: Removal of testis.',
  '7619: Removal of ovary.',
  '7618: Removal of uterus.',
  '7617: Removal of uterus and both ovaries.',
  '7539: Renal amyloid disease.',
  '7544: Renal disease caused by viral infection such as HIV, Hepatitis B, and Hepatitis C.',
  '7530: Renal disease, chronic.',
  '7541: Renal involvement in diabetes mellitus type I or II.',
  '7532: Renal tubular disorders.',
  '7328: Resection of intestine, small.',
  '7329: Resection of intestine, large.',
  '6008: Retina, detachment of.',
  '6042: Retinal dystrophy (including retinitis pigmentosa, wet or dry macular degeneration, early-onset macular degeneration, rod and/or cone dystrophy).',
  '6040: Retinopathy, diabetic.',
  '6006: Retinopathy or maculopathy not otherwise specified.',
  '5330: Rhabdomyolysis, residuals of.',
  '6522: Rhinitis, allergic or vasomotor.',
  '6523: Rhinitis, bacterial.',
  '6524: Rhinitis, granulomatous.',
  '6317: Rickettsial, ehrlichia, and anaplasma infections.',
  '6846: Sarcoidosis.',
  '7830: Scarring alopecia.',
  '7800: Scars, burn scar(s) of the head, face, or neck; scar(s) of the head, face, or neck due to other causes; or other disfigurement of the head, face, or neck.',
  '7801: Scars, burn scar(s) or scar(s) due to other causes, not of the head, face, or neck that are associated with underlying soft tissue damage.',
  '7802: Scars, burn scar(s) or scar(s) due to other causes, not of the head, face, or neck that are not associated with underlying soft tissue damage.',
  '6011: Scars, retina.',
  '7805: Scars, other; and other effects of scars evaluated under diagnostic codes 7800, 7801, 7802, or 7804.',
  '7804: Scars, unstable or painful.',
  '6326: Schistosomiasis.',
  '6334: Shigella infections.',
  '6511: Sinusitis, ethmoid.',
  '6512: Sinusitis, frontal.',
  '6513: Sinusitis, maxillary.',
  '6510: Sinusitis, pansinusitis.',
  '6514: Sinusitis, sphenoid.',
  '6847: Sleep Apnea Syndrome.',
  '5329: Soft tissue sarcoma, muscle, fat, or fibrous connected.',
  '8540: Soft tissue sarcoma, neurogenic origin.',
  '7123: Soft tissue sarcoma, vascular origin.',
  '5242: Spine, degenerative arthritis, degenerative disc disease other than intervertebral disc syndrome.',
  '5241: Spinal fusion.',
  '5238: Spinal stenosis.',
  '7707: Spleen, injury of, healed.',
  '7706: Splenectomy.',
  '5239: Spondylolisthesis or segmental instability, spine.',
  '7308: Stomach, postgastrectomy syndrome.',
  '7309: Stomach, stenosis of.',
  '7303: Stomach, surgery, complications of.',
  '7010: Supraventricular tachycardia.',
  '6091: Symblepharon.',
  '6354: Chronic Fatigue Syndrome (CFS).',
  "7907: Cushing's syndrome.",
  '7356: Gastrointestinal dysmotility syndrome.',
  "6205: Meniere's syndrome.",
  '7308: Postgastrectomy syndromes.',
  '7357: Post pancreatectomy syndrome.',
  "7117: Raynaud's syndrome.",
  '6847: Sleep Apnea Syndrome.',
  '6310: Syphilis.',
  '8013: Syphilis, cerebrospinal.',
  '8014: Syphilis, meningovascular.',
  '7004: Syphilitic heart disease.',
  '8024: Syringomyelia.',
  '8015: Tabes dorsalis.',
  '5283: Tarsal or metatarsal bones.',
  '5024: Tenosynovitis, tendinitis, tendinosis or tendinopathy.',
  '7523: Testis, atrophy, complete.',
  '7524: Testis, removal.',
  '7705: Thrombocytopenia.',
  '8008: Thrombosis, brain.',
  '7902: Thyroid gland, nontoxic thyroid enlargement.',
  '7901: Thyroid gland, toxic thyroid enlargement.',
  '7906: Thyroiditis.',
  '8103: Tic, convulsive.',
  '6260: Tinnitus, recurrent.',
  '7535: Toxic nephropathy.',
  '8045: Traumatic brain injury residuals.',
  '6843: Traumatic chest wall defect.',
  '7710: Tuberculosis, adenitis.',
  '5001: Tuberculosis, bones and joints.',
  '6010: Tuberculosis, eye.',
  '7505: Tuberculosis, kidney.',
  '7811: Tuberculosis, luposa (lupus vulgaris).',
  '6311: Tuberculosis, miliary.',
  '6732: Tuberculosis, pleurisy, active or inactive.',
  '6701: Tuberculosis, pulmonary, active, far advanced.',
  '6702: Tuberculosis, pulmonary, active, moderately advanced.',
  '6703: Tuberculosis, pulmonary, active, minimal.',
  '6704: Tuberculosis, pulmonary, active, advancement unspecified.',
  '6730: Tuberculosis, pulmonary, active, chronic.',
  '6731: Tuberculosis, pulmonary, inactive, chronic.',
  '6721: Tuberculosis, pulmonary, inactive, far advanced.',
  '6722: Tuberculosis, pulmonary, inactive, moderately advanced.',
  '6723: Tuberculosis, pulmonary, inactive, minimal.',
  '6724: Tuberculosis, pulmonary, inactive, advancement unspecified.',
  '6211: Tympanic membrane.',
  '7304: Ulcer, peptic.',
  '7511: Ureter, stricture of.',
  '7519: Urethra, fistula.',
  '7518: Urethra, stricture.',
  '7825: Urticaria, chronic.',
  '7611: Vagina, disease or injury.',
  '7348: Vagotomy.',
  '7000: Valvular heart disease.',
  '7543: Varicocele/Hydrocele.',
  '7120: Varicose veins.',
  '7826: Vasculitis, primary cutaneous.',
  '7011: Ventricular arrhythmia.',
  '5235: Vertebral fracture or dislocation.',
  '6300: Vibriosis (Cholera, Non-cholera).',
  '6301: Visceral Leishmaniasis.',
  '7342: Visceroptosis.',
  '6071: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 5/200 (1.5/60).',
  '6072: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6073: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6074: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 20/40 (6/12).',
  '6075: Vision, one eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60), with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6076: Vision, one eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60), with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6077: Vision, one eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60), with visual acuity of other eye 20/40 (6/12).',
  '6078: Vision, one eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15), with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6079: Vision, one eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15), with visual acuity of other eye 20/40 (6/12); or each eye 20/40 (6/12).',
  '7823: Vitiligo.',
  '7610: Vulva or clitoris, disease or injury of.',
  '5277: Weak foot.',
  '6335: West Nile virus infection.',
];

export const formsIdList = [
  {
    formId: 'fillform',
    formTitle: 'Submit Intent to File',
    formUrl: '/forms/submit-to-intent',
  },

  {
    formId: 'requestcfile',
    formTitle: 'Request C-File/DD 214 (Form 20-10206)',
    formUrl: '/forms/request-c-file',
  },

  {
    formId: 'ptsdform',
    formTitle: 'PTSD Stressor Statement (Form 21-0781)',
    formUrl: '/forms/ptsd-stressor',
  },
  {
    formId: 'supportofclaim',
    formTitle: 'Statement in Support of Claim (Form 21-4138)',
    formUrl: '/forms/ptsd-stressor',
  },
  {
    formId: 'medicalrecords',
    formTitle: 'Medical Records Release (Form 21-4142)',
    formUrl: '/forms/medical-records',
  },
  {
    formId: 'tdiuform',
    formTitle: 'Increased Rating due to TDIU (Unemployability) (Form 21-8940)',
    formUrl: '/forms/tdiu',
  },

  {
    formId: 'higherlevelreview',
    formTitle: 'Higher Level Review (Form 20-0996)',
    formUrl: '/forms/higher-level-review',
  },
  {
    formId: 'boardappeal',
    formTitle: 'Board Appeal (Form 20-0995)',
    formUrl: '/forms/board-appeal',
  },
  {
    formId: 'supplementalclaimAppeal',
    formTitle: 'Supplemental Claim Appeal',
    formUrl: '/forms/supplemental-claim',
  },

  {
    formId: 'courtform',
    formTitle: 'Notice of Appeal (NOA) & Optional Fee Waiver',
    formUrl: '/forms/noa',
  },
  {
    formId: 'financial_hardship',
    formTitle: 'Declaration of Financial Hardship (Fee Waiver)',
    formUrl: '/forms/fee-waiver',
  },

  {
    formId: 'newclaim',
    formTitle: 'New Claim or Increase (Form 21-526EZ)',
    formUrl: '/forms/new-claim',
  },
  {
    formId: 'supplementalclaim',
    formTitle: 'Supplemental Claim & Reopening (Form 20-0995)',
    formUrl: '/forms/supplemnetal-claim-reopening',
  },
];
