export const StateData = [
  {
    name: 'Alabama',
    abbreviation: 'AL',
    selected: false,
  },
  {
    name: 'Alaska',
    abbreviation: 'AK',
    selected: false,
  },
  {
    name: 'American Samoa',
    abbreviation: 'AS',
    selected: false,
  },
  {
    name: 'Arizona',
    abbreviation: 'AZ',
    selected: false,
  },
  {
    name: 'Arkansas',
    abbreviation: 'AR',
    selected: false,
  },
  {
    name: 'California',
    abbreviation: 'CA',
    selected: false,
  },
  {
    name: 'Colorado',
    abbreviation: 'CO',
    selected: false,
  },
  {
    name: 'Connecticut',
    abbreviation: 'CT',
    selected: false,
  },
  {
    name: 'Delaware',
    abbreviation: 'DE',
    selected: false,
  },
  {
    name: 'District Of Columbia',
    abbreviation: 'DC',
    selected: false,
  },
  {
    name: 'Federated States Of Micronesia',
    abbreviation: 'FM',
    selected: false,
  },
  {
    name: 'Florida',
    abbreviation: 'FL',
    selected: false,
  },
  {
    name: 'Georgia',
    abbreviation: 'GA',
    selected: false,
  },
  {
    name: 'Guam',
    abbreviation: 'GU',
    selected: false,
  },
  {
    name: 'Hawaii',
    abbreviation: 'HI',
    selected: false,
  },
  {
    name: 'Idaho',
    abbreviation: 'ID',
    selected: false,
  },
  {
    name: 'Illinois',
    abbreviation: 'IL',
    selected: false,
  },
  {
    name: 'Indiana',
    abbreviation: 'IN',
    selected: false,
  },
  {
    name: 'Iowa',
    abbreviation: 'IA',
    selected: false,
  },
  {
    name: 'Kansas',
    abbreviation: 'KS',
    selected: false,
  },
  {
    name: 'Kentucky',
    abbreviation: 'KY',
    selected: false,
  },
  {
    name: 'Louisiana',
    abbreviation: 'LA',
    selected: false,
  },
  {
    name: 'Maine',
    abbreviation: 'ME',
    selected: false,
  },
  {
    name: 'Marshall Islands',
    abbreviation: 'MH',
    selected: false,
  },
  {
    name: 'Maryland',
    abbreviation: 'MD',
    selected: false,
  },
  {
    name: 'Massachusetts',
    abbreviation: 'MA',
    selected: false,
  },
  {
    name: 'Michigan',
    abbreviation: 'MI',
    selected: false,
  },
  {
    name: 'Minnesota',
    abbreviation: 'MN',
    selected: false,
  },
  {
    name: 'Mississippi',
    abbreviation: 'MS',
    selected: false,
  },
  {
    name: 'Missouri',
    abbreviation: 'MO',
    selected: false,
  },
  {
    name: 'Montana',
    abbreviation: 'MT',
    selected: false,
  },
  {
    name: 'Nebraska',
    abbreviation: 'NE',
    selected: false,
  },
  {
    name: 'Nevada',
    abbreviation: 'NV',
    selected: false,
  },
  {
    name: 'New Hampshire',
    abbreviation: 'NH',
    selected: false,
  },
  {
    name: 'New Jersey',
    abbreviation: 'NJ',
    selected: false,
  },
  {
    name: 'New Mexico',
    abbreviation: 'NM',
    selected: false,
  },
  {
    name: 'New York',
    abbreviation: 'NY',
    selected: false,
  },
  {
    name: 'North Carolina',
    abbreviation: 'NC',
    selected: false,
  },
  {
    name: 'North Dakota',
    abbreviation: 'ND',
    selected: false,
  },
  {
    name: 'Northern Mariana Islands',
    abbreviation: 'MP',
    selected: false,
  },
  {
    name: 'Ohio',
    abbreviation: 'OH',
    selected: false,
  },
  {
    name: 'Oklahoma',
    abbreviation: 'OK',
    selected: false,
  },
  {
    name: 'Oregon',
    abbreviation: 'OR',
    selected: false,
  },
  {
    name: 'Palau',
    abbreviation: 'PW',
    selected: false,
  },
  {
    name: 'Pennsylvania',
    abbreviation: 'PA',
    selected: false,
  },
  {
    name: 'Puerto Rico',
    abbreviation: 'PR',
    selected: false,
  },
  {
    name: 'Rhode Island',
    abbreviation: 'RI',
    selected: false,
  },
  {
    name: 'South Carolina',
    abbreviation: 'SC',
    selected: false,
  },
  {
    name: 'South Dakota',
    abbreviation: 'SD',
    selected: false,
  },
  {
    name: 'Tennessee',
    abbreviation: 'TN',
    selected: false,
  },
  {
    name: 'Texas',
    abbreviation: 'TX',
    selected: false,
  },
  {
    name: 'Utah',
    abbreviation: 'UT',
    selected: false,
  },
  {
    name: 'Vermont',
    abbreviation: 'VT',
    selected: false,
  },
  {
    name: 'Virgin Islands',
    abbreviation: 'VI',
    selected: false,
  },
  {
    name: 'Virginia',
    abbreviation: 'VA',
    selected: false,
  },
  {
    name: 'Washington',
    abbreviation: 'WA',
    selected: false,
  },
  {
    name: 'West Virginia',
    abbreviation: 'WV',
    selected: false,
  },
  {
    name: 'Wisconsin',
    abbreviation: 'WI',
    selected: false,
  },
  {
    name: 'Wyoming',
    abbreviation: 'WY',
    selected: false,
  },
];

export const branchOfServiceData = [
  'Army',
  'Navy',
  'Marine Corps',
  'Air Force',
  'Coast Guard',
  'Space Force',
  'NOAA',
  'USPHA',
];

export const menuData = [
  {
    id: 'request_cfile',
    title: 'Request C-file/DD 214',
    status: true,
    submenu: [
      {
        id: 'req_cfile_1',
        title: 'Request C-File/DD 214 (Form 20-10206)',
        path: '/forms/request-c-file',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'misc_forms',
    title: 'Sworn Statements and Misc Forms',
    status: true,
    submenu: [
      {
        id: 'misc_1',
        title: 'PTSD Stressor Statement (Form 21-0781)',
        path: '/forms/ptsd-stressor',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'misc_2',
        title: 'Statement in Support of Claim (Form 21-4138)',
        path: '/forms/support-claim',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'misc_3',
        title: 'Medical Records Release (Form 21-4142)',
        path: '/forms/medical-records',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'misc_3',
        title: 'Increased Rating due to TDIU (Unemployability) (Form 21-8940)',
        path: '/forms/tdiu',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'file_appeal',
    title: 'File An Appeal',
    status: true,
    submenu: [
      {
        id: 'appeal_1',
        title: 'Higher Level Review (Form 20-0996)',
        path: '/forms/higher-level-review',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'appeal_2',
        title: 'Board Appeal (Form 10182)',
        path: '/forms/board-appeal',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'appeal_3',
        title: 'Supplemental Claim Appeal',
        path: '/forms/supplemental-claim',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'court_appeal',
    title: 'Court of Appeals for Veterans Claims-File Appeal',
    status: true,
    submenu: [
      {
        id: 'court_1',
        title: 'Notice of Appeal (NOA) & Optional Fee Waiver',
        path: '/forms/noa',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'court_2',
        title: 'Declaration of Financial Hardship (Fee Waiver)',
        path: '/forms/fee-waiver',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
  {
    id: 'submit_claim',
    title: 'Submit a Claim',
    status: true,
    submenu: [
      {
        id: 'claim_1',
        title: 'New Claim or Increase (Form 21-526EZ)',
        path: '/forms/new-claim',
        disabled: false,
        onPress: () => {},
      },
      {
        id: 'claim_2',
        title: 'Supplemental Claim & Reopening (Form 20-0995)',
        path: '/forms/supplemnetal-claim-reopening',
        disabled: false,
        onPress: () => {},
      },
    ],
  },
];

export const disabilityData = [
  '7335: Anorectal abscess.',
  '8020: Brain abscess.',
  '7501: Kidney abscess.',
  '7350: Liver abscess.',
  '6824: Lung abscess.',
  '7828: Acne.',
  '7908: Acromegaly.',
  '6822: Actinomycosis.',
  "7911: Addison's disease.",
  '7702: Agranulocytosis, acquired.',
  '7717: AL amyloidosis.',
  '7831: Alopecia areata.',
  '7321: Amebiasis.',
  '5120: Complete amputation, upper extremity.',
  '5121: Amputation above insertion of deltoid.',
  '5122: Amputation below insertion of deltoid.',
  '5126: Amputation of five digits of one hand.',
  '5127: Amputation of thumb, index, long and ring.',
  '5128: Amputation of thumb, index, long and little.',
  '5129: Amputation of thumb, index, ring and little.',
  '5130: Amputation of thumb, long, ring and little.',
  '5131: Amputation of index, long, ring and little.',
  '5132: Amputation of thumb, index and long.',
  '5133: Amputation of thumb, index and ring.',
  '5134: Amputation of thumb, index and little.',
  '5135: Amputation of thumb, long and ring.',
  '5136: Amputation of thumb, long and little.',
  '5137: Amputation of thumb, ring and little.',
  '5138: Amputation of index, long and ring.',
  '5139: Amputation of index, long and little.',
  '5140: Amputation of index, ring and little.',
  '5141: Amputation of long, ring and little.',
  '5142: Amputation of thumb and index.',
  '5143: Amputation of thumb and long.',
  '5144: Amputation of thumb and ring.',
  '5145: Amputation of thumb and little.',
  '5146: Amputation of index and long.',
  '5147: Amputation of index and ring.',
  '5148: Amputation of index and little.',
  '5149: Amputation of long and ring.',
  '5150: Amputation of long and little.',
  '5151: Amputation of ring and little.',
  '5152: Amputation of thumb.',
  '5153: Amputation of index finger.',
  '5154: Amputation of long finger.',
  '5155: Amputation of ring finger.',
  '5156: Amputation of little finger.',
  '5123: Amputation of forearm above insertion of pronator teres.',
  '5124: Amputation of forearm below insertion of pronator teres.',
  '5163: Amputation of leg with defective stump.',
  '5164: Amputation of leg not improvable by prosthesis controlled by natural knee action.',
  '5165: Amputation of leg at lower level, permitting prosthesis.',
  '5166: Amputation of forefoot, proximal to metatarsal bones.',
  '5170: Amputation of all toes, without metatarsal loss or transmetatarsal, with up to half of metatarsal loss.',
  '5171: Amputation of great toe.',
  '5172: Amputation of toe, other than great, with removal of metatarsal head.',
  '5173: Amputation of three or more toes, without metatarsal involvement.',
  '5160: Complete amputation, lower extremity.',
  '5161: Amputation of thigh, upper third.',
  '5162: Amputation of thigh, middle or lower thirds.',
  '8017: Amyotrophic lateral sclerosis.',
  '6061: Anatomical loss of both eyes.',
  '6063: Anatomical loss of one eye, with visual acuity of other eye 5/200 (1.5/60).',
  '6064: Anatomical loss of one eye, with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6065: Anatomical loss of one eye, with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6066: Anatomical loss of one eye, with visual acuity of other eye 20/40 (6/12).',
  '5107: Anatomical loss of both feet.',
  '5106: Anatomical loss of both hands.',
  '5108: Anatomical loss of one hand and one foot.',
  '5105: Anatomical loss of one foot and loss of use of one hand.',
  '5104: Anatomical loss of one hand and loss of use of one foot.',
  '7723: Acquired hemolytic anemia.',
  '7721: Folic acid deficiency.',
  '7720: Iron deficiency anemia.',
  '7722: Pernicious anemia and Vitamin B12 deficiency anemia.',
  '7110: Aortic aneurysm, ascending, thoracic, abdominal.',
  '7111: Aneurysm, large artery.',
  '7118: Aneurysm, small artery.',
  '5270: Ankylosis of ankle.',
  '5224: Ankylosis of thumb.',
  '5225: Ankylosis of index finger.',
  '5226: Ankylosis of long finger.',
  '5227: Ankylosis of ring or little finger.',
  '5205: Ankylosis of elbow.',
  '5220: Ankylosis of five digits of one hand, favorable.',
  '5221: Ankylosis of four digits of one hand, favorable.',
  '5222: Ankylosis of three digits of one hand, favorable.',
  '5223: Ankylosis of two digits of one hand, favorable.',
  '5216: Ankylosis of five digits of one hand, unfavorable.',
  '5217: Ankylosis of four digits of one hand, unfavorable.',
  '5218: Ankylosis of three digits of one hand, unfavorable.',
  '5219: Ankylosis of two digits of one hand, unfavorable.',
  '5250: Ankylosis of hip.',
  '5256: Ankylosis of knee.',
  '5200: Ankylosis of scapulohumeral articulation.',
  '5272: Ankylosis of subastragalar or tarsal joint.',
  '5214: Ankylosis of wrist.',
  '5240: Ankylosing spondylitis.',
  '6029: Aphakia.',
  '6519: Aphonia, organic.',
  '7716: Aplastic anemia.',
  '7005: Arteriosclerotic heart disease.',
  '7113: Arteriovenous fistula.',
  '5003: Arthritis, degenerative, other than post-traumatic.',
  '5004: Arthritis, gonorrheal.',
  '5009: Arthritis, other specified forms (excluding gout).',
  '5005: Arthritis, pneumococcic.',
  '5010: Arthritis, post-traumatic.',
  '5002: Arthritis, multi-joint (except post-traumatic and gout).',
  '5008: Arthritis, streptococcic.',
  '5007: Arthritis, syphilitic.',
  '5006: Arthritis, typhoid.',
  '5009: Arthropathy.',
  '6833: Asbestosis.',
  '6838: Aspergillosis.',
  '6602: Asthma, bronchial.',
  '5274: Astragalectomy.',
  '7534: Atherosclerotic renal disease.',
  '8107: Athetosis.',
  '7015: Atrioventricular block.',
  '6313: Avitaminosis.',
  '6306: Bartonellosis.',
  '6314: Beriberi.',
  '7515: Bladder, calculus in.',
  '7545: Bladder, diverticulum of.',
  '7516: Bladder, fistula in.',
  '7517: Bladder, injury of.',
  '7542: Bladder, neurogenic.',
  '6836: Blastomycosis.',
  '6062: Blindness, both eyes, only light perception.',
  '6067: Blindness, one eye, only light perception, with visual acuity of other eye 5/200 (1.5/60).',
  '6068: Blindness, one eye, only light perception, with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6069: Blindness, one eye, only light perception, with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6070: Blindness, one eye, only light perception, with visual acuity of other eye 20/40 (6/12).',
  '5015: Bones, neoplasm, benign.',
  '5012: Bones, neoplasm, malignant, primary or secondary.',
  '5275: Bones, shortening of the lower extremity.',
  '7009: Bradycardia (Bradyarrhythmia), symptomatic, requiring permanent pacemaker implantation.',
  '8020: Brain abscess.',
  '7631: Breast, benign neoplasms.',
  '7626: Breast surgery.',
  '6601: Bronchiectasis.',
  '6600: Bronchitis.',
  '6316: Brucellosis.',
  "7115: Buerger's disease.",
  '8005: Bulbar palsy.',
  '7815: Bullous disorders.',
  '5019: Bursitis.',
  '6330: Campylobacter jejuni infection.',
  '7018: Cardiac pacemakers, implantable.',
  '7019: Cardiac transplantation.',
  '7020: Cardiomyopathy.',
  '7919: C-cell hyperplasia, thyroid.',
  '6028: Cataract, senile and others.',
  '6027: Cataract, traumatic.',
  '8046: Cerebral arteriosclerosis.',
  '5237: Cervical strain.',
  '7612: Cervix disease or injury.',
  "8106: Chorea, Huntington's.",
  "8105: Chorea, Sydenham's.",
  '7829: Chloracne.',
  '7314: Cholangitis, chronic.',
  '7318: Cholecystectomy (gallbladder removal), complications of (such as strictures and biliary leaks).',
  '7314: Cholecystitis, chronic.',
  '7315: Cholelithiasis, chronic.',
  '6005: Choroiditis.',
  '6354: Chronic Fatigue Syndrome (CFS).',
  '6824: Chronic lung abscess.',
  '6604: Chronic obstructive pulmonary disease.',
  '6835: Coccidioidomycosis.',
  '7122: Cold injury residuals.',
  '7323: Colitis, ulcerative.',
  '5331: Compartment syndrome.',
  '7621: Complete or incomplete pelvic organ prolapse due to injury or disease or surgical complications of pregnancy, including uterine or vaginal vault prolapse, cystocele, urethrocele, rectocele, enterocele, or combination.',
  '6017: Conjunctivitis, trachomatous.',
  '6018: Conjunctivitis, other.',
  '7017: Coronary bypass surgery.',
  '6331: Coxiella burnetii infection (Q Fever).',
  '6837: Cryptococcosis.',
  "7907: Cushing's syndrome.",
  '7821: Cutaneous manifestations of collagen-vascular diseases not listed elsewhere.',
  '6004: Cyclitis.',
  '7512: Cystitis, chronic.',
  '6031: Dacryocystitis.',
  '5011: Decompression illness.',
  '7806: Dermatitis or eczema.',
  '7813: Dermatophytosis.',
  '5324: Diaphragm, rupture.',
  '6840: Diaphragm, paralysis or paresis.',
  '6090: Diplopia.',
  '6092: Diplopia, limited muscle function, eye.',
  "7911: Addison's disease.",
  "7115: Buerger's disease.",
  '7355: Celiac disease.',
  "7326: Crohn's disease.",
  '7314: Gallbladder and biliary tract, chronic.',
  "7709: Hodgkin's disease.",
  "6302: Leprosy (Hansen's Disease).",
  '6319: Lyme disease.',
  "5279: Morton's disease.",
  '6320: Parasitic disease.',
  '7800: Disfigurement of head, face or neck.',
  '5258: Dislocated cartilage, semilunar.',
  '6033: Dislocated lens, crystalline.',
  '7540: Disseminated intravascular coagulation.',
  '7324: Distomiasis, intestinal or hepatic.',
  '7322: Dysentery, bacillary.',
  '6020: Ectropion.',
  '8007: Embolism, brain.',
  '6603: Emphysema, pulmonary.',
  '8000: Encephalitis, epidemic, chronic.',
  '7001: Endocarditis.',
  '7629: Endometriosis.',
  '7325: Enteritis, chronic.',
  '7326: Enterocolitis, chronic.',
  '6021: Entropion.',
  '6828: Eosinophilic granuloma of lung.',
  '8913: Epilepsy, diencephalic.',
  '8910: Epilepsy, grand mal.',
  '8912: Epilepsy, Jacksonian and focal motor or sensory.',
  '8911: Epilepsy, petit mal.',
  '8914: Epilepsy, psychomotor.',
  '6025: Epiphora.',
  '7827: Erythema multiforme.',
  '7817: Erythroderma.',
  '7119: Erythromelalgia.',
  "7207: Barrett's esophagus.",
  '7205: Esophagus, diverticulum.',
  '7204: Esophagus, motility disorder.',
  '7203: Esophagus, stricture.',
  '7614: Fallopian tube.',
  '7632: Female sexual arousal disorder (FSAD).',
  '6308: Relapsing fever.',
  '6309: Rheumatic fever.',
  '6825: Fibrosis of lung, diffuse interstitial.',
  '5025: Fibromyalgia.',
  '7335: Fistula in ano.',
  '7624: Fistula, rectovaginal.',
  '7625: Fistula, urethrovaginal.',
  '5276: Flatfoot, acquired.',
  '7307: Gastritis, chronic.',
  '7206: Gastroesophageal reflux disease.',
  '5263: Genu recurvatum.',
  '6012: Glaucoma, congestive or inflammatory.',
  '6013: Glaucoma, simple, primary, noncongestive.',
  '7536: Glomerulonephritis.',
  '5017: Gout.',
  "7900: Graves' disease.",
  '5281: Hallux rigidus.',
  '5280: Hallux valgus.',
  '5282: Hammer toe.',
  '7016: Heart valve replacement.',
  '7718: Essential thrombocythemia and primary myelofibrosis.',
  '7705: Immune thrombocytopenia.',
  '7712: Multiple myeloma.',
  '7725: Myelodysplastic syndromes.',
  '7724: Solitary plasmacytoma.',
  '8012: Hematomyelia.',
  '6007: Hemorrhage, intra-ocular.',
  '6329: Hemorrhagic fevers, including dengue, yellow fever, and others.',
  '7336: Hemorrhoids.',
  '7354: Hepatitis C.',
  '7338: Hernia, femoral, inguinal, umbilical, ventral, incisional, and other.',
  '7346: Hernia, hiatal and paraesophageal.',
  '5326: Hernia, muscle.',
  '5023: Heterotopic ossification.',
  '5254: Hip, flail joint.',
  '6351: HIV-Related Illness.',
  "7709: Hodgkin's lymphoma.",
  '7509: Hydronephrosis.',
  '7917: Hyperaldosteronism.',
  '7832: Hyperhidrosis.',
  '7904: Hyperparathyroidism.',
  '7916: Hyperpituitarism.',
  '7007: Hypertensive heart disease.',
  '7101: Hypertensive vascular disease.',
  '7008: Hyperthyroid heart disease.',
  '7900: Hyperthyroidism.',
  '7905: Hypoparathyroidism.',
  '7903: Hypothyroidism.',
  '5202: Impairment of humerus.',
  '5203: Impairment of clavicle or scapula.',
  '5209: Impairment of elbow.',
  '5253: Impairment of thigh.',
  '5255: Impairment of femur.',
  '5257: Impairment of knee, other.',
  '6080: Impairment of field vision.',
  '5262: Impairment of tibia and fibula.',
  '7332: Impairment of rectum and anus.',
  '5211: Impairment of ulna.',
  '7018: Implantable cardiac pacemakers.',
  '7820: Infections of the skin.',
  '7517: Injury of bladder.',
  '7631: Injury of breast.',
  '6009: Injury of eye, unhealed.',
  '5284: Injury of foot.',
  '7317: Injury of gallbladder.',
  '7201: Injury of lips.',
  '7311: Injury of liver, residuals.',
  '7200: Injury of mouth, soft tissue.',
  '5301: Muscle injury, Group I Function: Upward rotation of scapula.',
  '5302: Muscle injury, Group II Function: Depression of arm.',
  '5303: Muscle injury, Group III Function: Elevation and abduction of arm.',
  '5304: Muscle injury, Group IV Function: Stabilization of shoulder.',
  '5305: Muscle injury, Group V Function: Elbow supination.',
  '5306: Muscle injury, Group VI Function: Extension of elbow.',
  '5307: Muscle injury, Group VII Function: Flexion of wrist and fingers.',
  '5308: Muscle injury, Group VIII Function: Extension of wrist, fingers, thumb.',
  '5309: Muscle injury, Group IX Function: Forearm muscles.',
  '5310: Muscle injury, Group X Function: Movement of forefoot and toes.',
  '5311: Muscle injury, Group XI Function: Propulsion of foot.',
  '5312: Muscle injury, Group XII Function: Dorsiflexion.',
  '5313: Muscle injury, Group XIII Function: Extension of hip and flexion of knee.',
  '5314: Muscle injury, Group XIV Function: Extension of knee.',
  '5315: Muscle injury, Group XV Function: Adduction of hip.',
  '5316: Muscle injury, Group XVI Function: Flexion of hip.',
  '5317: Muscle injury, Group XVII Function: Extension of hip.',
  '5318: Muscle injury, Group XVIII Function: Outward rotation of thigh.',
  '5319: Muscle injury, Group XIX Function: Abdominal wall and lower thorax.',
  '5320: Muscle injury, Group XX Function: Postural support of body.',
  '5321: Muscle injury, Group XXI Function: Respiration.',
  '5322: Muscle injury, Group XXII Function: Rotary and forward movements, head.',
  '5323: Muscle injury, Group XXIII Function: Movements of head.',
  '6521: Injury of pharynx.',
  '5236: Injury of sacroiliac.',
  '6841: Injury of spinal cord.',
  '7310: Injury of stomach, residuals.',
  '6003: Iritis.',
  '7537: Interstitial nephritis, including gouty nephropathy, disorders of calcium metabolism.',
  '5243: Intervertebral disc syndrome.',
  '7330: Intestine, fistulous disease, external.',
  '7329: Intestine, large, resection of.',
  '7328: Intestine, small, resection of.',
  '7319: Irritable bowel syndrome (IBS).',
  '7824: Keratinization, diseases of.',
  '6001: Keratitis.',
  '6035: Keratoconus.',
  '7501: Kidney abscess.',
  '7533: Kidney, cystic diseases.',
  '7500: Kidney, removal.',
  '7531: Kidney transplant.',
  '7505: Kidney, tuberculosis.',
  '6842: Kyphoscoliosis, pectus excavatum/carinatum.',
  '6022: Lagophthalmos.',
  '6518: Laryngectomy.',
  '6515: Laryngitis, tuberculous.',
  '6516: Laryngitis, chronic.',
  '6520: Larynx, stenosis of.',
  '7807: Leishmaniasis, American (New World).',
  '7808: Leishmaniasis, Old World.',
  "6302: Leprosy (Hansen's Disease).",
  '7703: Leukemia.',
  '7719: Chronic myelogenous leukemia (CML).',
  '5207: Limitation of extension, forearm.',
  '5261: Limitation of extension, leg.',
  '5212: Limitation of extension, radius.',
  '5213: Limitation of supination and pronation.',
  '5251: Limitation of extension, thigh.',
  '5208: Limitation of extension and flexion, forearm.',
  '5206: Limitation of flexion, forearm.',
  '5260: Limitation of flexion, leg.',
  '5252: Limitation of flexion, thigh.',
  '5271: Limitation of motion, ankle.',
  '5201: Limitation of motion, arm.',
  '5229: Limitation of motion, index or long finger.',
  '5230: Limitation of motion, ring or little finger.',
  '9905: Limitation of motion, temporomandibular.',
  '5228: Limitation of motion, thumb.',
  '5215: Limitation of motion, wrist.',
  '7345: Liver disease, chronic, without cirrhosis.',
  '7351: Liver transplant.',
  '7312: Liver, cirrhosis.',
  '6207: Loss of auricle.',
  '9908: Loss of condyloid process.',
  '9909: Loss of coronoid process.',
  '6023: Loss of eyebrows.',
  '6024: Loss of eyelashes.',
  '6032: Loss of eyelids.',
  '9911: Loss of palate, hard.',
  '9902: Loss of mandible, including ramus, unilaterally or bilaterally.',
  '9914: Loss of maxilla, more than half.',
  '9915: Loss of maxilla, less than half.',
  '6504: Loss of nose, part of, or scars.',
  '5296: Loss of skull, part of.',
  '6275: Loss of smell, sense of.',
  '6276: Loss of taste, sense of.',
  '9913: Loss of teeth.',
  '7202: Loss of tongue, whole or part.',
  '5110: Loss of use of both feet.',
  '5109: Loss of use of both hands.',
  '5167: Loss of use of foot.',
  '5125: Loss of use of hand.',
  '5111: Loss of use of one hand and one foot.',
  '5237: Lumbosacral strain.',
  '6350: Lupus erythematosus.',
  '7809: Lupus erythematosus, discoid.',
  '6319: Lyme disease.',
  '6304: Malaria.',
  '7833: Malignant melanoma.',
  '9904: Malunion of mandible.',
  '5273: Malunion of os calcis or astragalus.',
  '9916: Malunion or nonunion of maxilla.',
  '9900: Maxilla or mandible, chronic osteomyelitis, osteonecrosis, or osteoradionecrosis of.',
  '6318: Melioidosis.',
  "6205: Meniere's syndrome.",
  '8019: Meningitis, cerebrospinal, epidemic.',
  '9520: Anorexia nervosa.',
  '9432: Bipolar disorder.',
  '9521: Bulimia nervosa.',
  '9440: Chronic adjustment disorder.',
  '9424: Conversion disorder (functional neurological symptom disorder).',
  '9431: Cyclothymic disorder.',
  '9300: Delirium.',
  '9208: Delusional disorder.',
  '9417: Depersonalization/derealization disorder.',
  '9416: Dissociative amnesia; dissociative identity disorder.',
  '9400: Generalized anxiety disorder.',
  '9425: Illness anxiety disorder.',
  '9434: Major depressive disorder.',
  "9312: Major or mild neurocognitive disorder due to Alzheimer's disease.",
  '9326: Major or mild neurocognitive disorder due to another medical condition or substance/medication-induced.',
  '9301: Major or mild neurocognitive disorder due to HIV or other infections.',
  '9304: Major or mild neurocognitive disorder due to traumatic brain injury.',
  '9305: Major or mild vascular neurocognitive disorder.',
  '9404: Obsessive compulsive disorder.',
  '9210: Other specified and unspecified schizophrenia spectrum and other psychotic disorders.',
  '9410: Other specified anxiety disorder.',
  '9422: Other specified somatic symptom and related disorder.',
  '9412: Panic disorder and/or agoraphobia.',
  '9433: Persistent depressive disorder (dysthymia).',
  '9411: Posttraumatic stress disorder.',
  '9211: Schizoaffective disorder.',
  '9201: Schizophrenia.',
  '9421: Somatic symptom disorder.',
  '9403: Specific phobia; social anxiety disorder (social phobia).',
  '9423: Unspecified somatic symptom and related disorder.',
  '9413: Unspecified anxiety disorder.',
  '9435: Unspecified depressive disorder.',
  '9310: Unspecified neurocognitive disorder.',
  '5279: Metatarsalgia.',
  '8100: Migraine.',
  '6839: Mucormycosis.',
  '8018: Multiple sclerosis.',
  '8010: Myelitis.',
  '7006: Myocardial infarction.',
  '5021: Myositis.',
  '8108: Narcolepsy.',
  '7631: Neoplasms, benign, breast.',
  '7344: Neoplasms, benign, digestive system.',
  '6209: Neoplasms, benign, ear.',
  '7915: Neoplasms, benign, endocrine.',
  '7529: Neoplasms, benign, genitourinary.',
  '7628: Neoplasms, benign, gynecological.',
  '9917: Neoplasms, benign, hard and soft tissue.',
  '5328: Neoplasms, benign, muscle.',
  '6820: Neoplasms, benign, respiratory.',
  '7819: Neoplasms, benign, skin.',
  '7630: Neoplasms, malignant, breast.',
  '7343: Neoplasms, malignant, digestive system.',
  '6208: Neoplasms, malignant, ear.',
  '7914: Neoplasms, malignant, endocrine.',
  '7528: Neoplasms, malignant, genitourinary.',
  '7627: Neoplasms, malignant, gynecological.',
  '9918: Neoplasms, malignant, hard and soft tissue.',
  '5327: Neoplasms, malignant, muscle.',
  '6819: Neoplasms, malignant, respiratory.',
  '7818: Neoplasms, malignant, skin.',
  '7502: Nephritis, chronic.',
  '7508: Nephrolithiasis/Ureterolithiasis/Nephrocalcinosis.',
  '7507: Nephrosclerosis, arteriolar.',
  '8405: Neuralgia, fifth (trigeminal) cranial nerve.',
  '8407: Neuralgia, seventh (facial) cranial nerve.',
  '8409: Neuralgia, ninth (glossopharyngeal) cranial nerve.',
  '8410: Neuralgia, tenth (pneumogastric, vagus) cranial nerve.',
  '8411: Neuralgia, eleventh (spinal accessory, external branch) cranial nerve.',
  '8412: Neuralgia, twelfth (hypoglossal) cranial nerve.',
  '8710: Neuralgia, upper radicular group, peripheral nerve.',
  '8711: Neuralgia, middle radicular group, peripheral nerve.',
  '8712: Neuralgia, lower radicular group, peripheral nerve.',
  '8713: Neuralgia, all radicular groups, peripheral nerve.',
  '8714: Neuralgia, musculospiral (radial), peripheral nerve.',
  '8715: Neuralgia, median, peripheral nerve.',
  '8716: Neuralgia, ulnar, peripheral nerve.',
  '8717: Neuralgia, musculocutaneous, peripheral nerve.',
  '8718: Neuralgia, circumflex, peripheral nerve.',
  '8719: Neuralgia, long thoracic, peripheral nerve.',
  '8720: Neuralgia, sciatic, peripheral nerve.',
  '8721: Neuralgia, external popliteal (common peroneal), peripheral nerve.',
  '8722: Neuralgia, musculocutaneous (superficial peroneal), peripheral nerve.',
  '8723: Neuralgia, anterior tibial (deep peroneal), peripheral nerve.',
  '8724: Neuralgia, internal popliteal (tibial), peripheral nerve.',
  '8725: Neuralgia, posterior tibial, peripheral nerve.',
  '8726: Neuralgia, anterior crural (femoral), peripheral nerve.',
  '8727: Neuralgia, internal saphenous, peripheral nerve.',
  '8728: Neuralgia, obturator, peripheral nerve.',
  '8729: Neuralgia, external cutaneous nerve of thigh, peripheral nerve.',
  '8730: Neuralgia, ilio-inguinal, peripheral nerve.',
  '6026: Neuritis, optic.',
  '8610: Neuritis, upper radicular group, peripheral nerve.',
  '8611: Neuritis, middle radicular group, peripheral nerve.',
  '8612: Neuritis, lower radicular group, peripheral nerve.',
  '8613: Neuritis, all radicular groups, peripheral nerve.',
  '8614: Neuritis, musculospiral (radial), peripheral nerve.',
  '8615: Neuritis, median, peripheral nerve.',
  '8616: Neuritis, ulnar, peripheral nerve.',
  '8617: Neuritis, musculocutaneous, peripheral nerve.',
  '8618: Neuritis, circumflex, peripheral nerve.',
  '8619: Neuritis, long thoracic, peripheral nerve.',
  '8620: Neuritis, sciatic, peripheral nerve.',
  '8621: Neuritis, external popliteal (common peroneal), peripheral nerve.',
  '8622: Neuritis, musculocutaneous (superficial peroneal), peripheral nerve.',
  '8623: Neuritis, anterior tibial (deep peroneal), peripheral nerve.',
  '8624: Neuritis, internal popliteal (tibial), peripheral nerve.',
  '8625: Neuritis, posterior tibial, peripheral nerve.',
  '8626: Neuritis, anterior crural (femoral), peripheral nerve.',
  '8627: Neuritis, internal saphenous, peripheral nerve.',
  '8628: Neuritis, obturator, peripheral nerve.',
  '8629: Neuritis, external cutaneous nerve of thigh, peripheral nerve.',
  '8630: Neuritis, ilio-inguinal, peripheral nerve.',
  '7542: Neurogenic bladder.',
  '5015: New growths, benign, bones.',
  '8003: New growths, benign, brain.',
  '6015: New growths, benign, eye, orbit, and adnexa.',
  '8022: New growths, benign, spinal cord.',
  '5012: New growths, malignant, bones.',
  '8002: New growths, malignant, brain.',
  '6014: New growths, malignant, eye, orbit, and adnexa.',
  '8021: New growths, malignant, spinal cord.',
  '6823: Nocardiosis.',
  "7715: Non-Hodgkin's lymphoma.",
  '6312: Nontuberculosis mycobacterium infection.',
  '6333: Nontyphoid salmonella infection.',
  '9903: Nonunion of mandible, confirmed by diagnostic imaging studies.',
  '5210: Nonunion of radius and ulna.',
  '6016: Nystagmus, central.',
  '5016: Osteitis deformans.',
  '5014: Osteomalacia, residuals of.',
  '5000: Osteomyelitis.',
  '5013: Osteoporosis, residuals of.',
  '6210: Otitis media, externa.',
  '6201: Otitis media, nonsuppurative.',
  '6200: Otitis media, suppurative.',
  '6202: Otosclerosis.',
  '7620: Ovaries, atrophy of both.',
  '7615: Ovary, disease or injury.',
  '7619: Ovary, removal.',
  '8005: Palsy, bulbar.',
  '7347: Pancreas, chronic pancreatitis.',
  '7357: Pancreas, post pancreatectomy syndrome.',
  '7303: Pancreas, surgery, complications of.',
  '7352: Pancreas, transplant.',
  '7538: Papillary necrosis.',
  '7822: Papulosquamous disorders.',
  '6030: Paralysis, accommodation.',
  '8004: Paralysis agitans.',
  '5244: Paralysis, complete, traumatic.',
  '8205: Paralysis, fifth (trigeminal) cranial nerve.',
  '8207: Paralysis, seventh (facial) cranial nerve.',
  '8209: Paralysis, ninth (glossopharyngeal) cranial nerve.',
  '8210: Paralysis, tenth (pneumogastric, vagus) cranial nerve.',
  '8211: Paralysis, eleventh (spinal accessory, external branch) cranial nerve.',
  '8212: Paralysis, twelfth (hypoglossal) cranial nerve.',
  '8510: Paralysis, upper radicular group, peripheral nerve.',
  '8511: Paralysis, middle radicular group, peripheral nerve.',
  '8512: Paralysis, lower radicular group, peripheral nerve.',
  '8513: Paralysis, all radicular groups, peripheral nerve.',
  '8514: Paralysis, musculospiral (radial), peripheral nerve.',
  '8515: Paralysis, median, peripheral nerve.',
  '8516: Paralysis, ulnar, peripheral nerve.',
  '8517: Paralysis, musculocutaneous, peripheral nerve.',
  '8518: Paralysis, circumflex, peripheral nerve.',
  '8519: Paralysis, long thoracic, peripheral nerve.',
  '8520: Paralysis, sciatic, peripheral nerve.',
  '8521: Paralysis, external popliteal (common peroneal), peripheral nerve.',
  '8522: Paralysis, musculocutaneous (superficial peroneal), peripheral nerve.',
  '8523: Paralysis, anterior tibial nerve (deep peroneal), peripheral nerve.',
  '8524: Paralysis, internal popliteal (tibial), peripheral nerve.',
  '8525: Paralysis, posterior tibial nerve, peripheral nerve.',
  '8526: Paralysis, anterior crural nerve (femoral), peripheral nerve.',
  '8527: Paralysis, internal saphenous, peripheral nerve.',
  '8528: Paralysis, obturator, peripheral nerve.',
  '8529: Paralysis, external cutaneous nerve of thigh, peripheral nerve.',
  '8530: Paralysis, ilio-inguinal, peripheral nerve.',
  '8104: Paramyoclonus multiplex.',
  '6320: Parasitic disease.',
  '6315: Pellagra.',
  '7522: Penis, erectile dysfunction.',
  '7521: Penis, removal of glans.',
  '7520: Penis, removal of half or more.',
  '7003: Pericardial adhesions.',
  '7002: Pericarditis.',
  '7114: Peripheral arterial disease.',
  '6204: Peripheral vestibular disorders.',
  '7301: Peritoneum, adhesions.',
  '7331: Peritonitis.',
  '5278: Pes cavus (Claw foot), acquired.',
  '7918: Pheochromocytoma.',
  '6307: Plague.',
  '5269: Plantar fasciitis.',
  '6845: Pleural effusion or fibrosis.',
  '7912: Pluriglandular syndrome.',
  '6832: Pneumoconiosis.',
  '6829: Pneumonitis & fibrosis, drug-induced.',
  '6830: Pneumonitis & fibrosis, radiation-induced.',
  '8011: Poliomyelitis, anterior.',
  '7704: Polycythemia vera.',
  '7912: Polyglandular syndrome.',
  '6046: Post-chiasmal disorders.',
  '7308: Postgastrectomy syndromes.',
  '7121: Post-phlebitic syndrome.',
  '6844: Post-surgical residual.',
  '8023: Progressive muscular atrophy.',
  '7527: Prostate gland injuries, infections, hypertrophy, postoperative residuals, bladder outlet obstruction.',
  '7525: Prostatitis, urethritis, epididymitis, orchitis (unilateral or bilateral), chronic only.',
  '5056: Prosthetic implants, ankle replacement.',
  '5052: Prosthetic implants, elbow replacement.',
  '5054: Prosthetic implants, hip, resurfacing or replacement.',
  '5055: Prosthetic implants, knee, resurfacing or replacement.',
  '5051: Prosthetic implants, shoulder replacement.',
  '5053: Prosthetic implants, wrist replacement.',
  '7816: Psoriasis.',
  '6034: Pterygium.',
  '6019: Ptosis.',
  '6817: Pulmonary vascular disease.',
  '7337: Pruritus ani (anal itching).',
  '7504: Pyelonephritis, chronic.',
  "7124: Raynaud's disease (primary Raynaud's).",
  "7117: Raynaud's syndrome (secondary Raynaud's phenomenon, secondary Raynaud's).",
  '7333: Rectum & anus, stricture.',
  '7334: Rectum, prolapse.',
  '5259: Removal of cartilage, semilunar.',
  '5298: Removal of coccyx.',
  '7318: Removal of gall bladder.',
  '7500: Removal of kidney.',
  '7521: Removal of penis glans.',
  '7520: Removal of penis half or more.',
  '5297: Removal of ribs.',
  '7524: Removal of testis.',
  '7619: Removal of ovary.',
  '7618: Removal of uterus.',
  '7617: Removal of uterus and both ovaries.',
  '7539: Renal amyloid disease.',
  '7544: Renal disease caused by viral infection such as HIV, Hepatitis B, and Hepatitis C.',
  '7530: Renal disease, chronic.',
  '7541: Renal involvement in diabetes mellitus type I or II.',
  '7532: Renal tubular disorders.',
  '7328: Resection of intestine, small.',
  '7329: Resection of intestine, large.',
  '6008: Retina, detachment of.',
  '6042: Retinal dystrophy (including retinitis pigmentosa, wet or dry macular degeneration, early-onset macular degeneration, rod and/or cone dystrophy).',
  '6040: Retinopathy, diabetic.',
  '6006: Retinopathy or maculopathy not otherwise specified.',
  '5330: Rhabdomyolysis, residuals of.',
  '6522: Rhinitis, allergic or vasomotor.',
  '6523: Rhinitis, bacterial.',
  '6524: Rhinitis, granulomatous.',
  '6317: Rickettsial, ehrlichia, and anaplasma infections.',
  '6846: Sarcoidosis.',
  '7830: Scarring alopecia.',
  '7800: Scars, burn scar(s) of the head, face, or neck; scar(s) of the head, face, or neck due to other causes; or other disfigurement of the head, face, or neck.',
  '7801: Scars, burn scar(s) or scar(s) due to other causes, not of the head, face, or neck that are associated with underlying soft tissue damage.',
  '7802: Scars, burn scar(s) or scar(s) due to other causes, not of the head, face, or neck that are not associated with underlying soft tissue damage.',
  '6011: Scars, retina.',
  '7805: Scars, other; and other effects of scars evaluated under diagnostic codes 7800, 7801, 7802, or 7804.',
  '7804: Scars, unstable or painful.',
  '6326: Schistosomiasis.',
  '6334: Shigella infections.',
  '6511: Sinusitis, ethmoid.',
  '6512: Sinusitis, frontal.',
  '6513: Sinusitis, maxillary.',
  '6510: Sinusitis, pansinusitis.',
  '6514: Sinusitis, sphenoid.',
  '6847: Sleep Apnea Syndrome.',
  '5329: Soft tissue sarcoma, muscle, fat, or fibrous connected.',
  '8540: Soft tissue sarcoma, neurogenic origin.',
  '7123: Soft tissue sarcoma, vascular origin.',
  '5242: Spine, degenerative arthritis, degenerative disc disease other than intervertebral disc syndrome.',
  '5241: Spinal fusion.',
  '5238: Spinal stenosis.',
  '7707: Spleen, injury of, healed.',
  '7706: Splenectomy.',
  '5239: Spondylolisthesis or segmental instability, spine.',
  '7308: Stomach, postgastrectomy syndrome.',
  '7309: Stomach, stenosis of.',
  '7303: Stomach, surgery, complications of.',
  '7010: Supraventricular tachycardia.',
  '6091: Symblepharon.',
  '6354: Chronic Fatigue Syndrome (CFS).',
  "7907: Cushing's syndrome.",
  '7356: Gastrointestinal dysmotility syndrome.',
  "6205: Meniere's syndrome.",
  '7308: Postgastrectomy syndromes.',
  '7357: Post pancreatectomy syndrome.',
  "7117: Raynaud's syndrome.",
  '6847: Sleep Apnea Syndrome.',
  '6310: Syphilis.',
  '8013: Syphilis, cerebrospinal.',
  '8014: Syphilis, meningovascular.',
  '7004: Syphilitic heart disease.',
  '8024: Syringomyelia.',
  '8015: Tabes dorsalis.',
  '5283: Tarsal or metatarsal bones.',
  '5024: Tenosynovitis, tendinitis, tendinosis or tendinopathy.',
  '7523: Testis, atrophy, complete.',
  '7524: Testis, removal.',
  '7705: Thrombocytopenia.',
  '8008: Thrombosis, brain.',
  '7902: Thyroid gland, nontoxic thyroid enlargement.',
  '7901: Thyroid gland, toxic thyroid enlargement.',
  '7906: Thyroiditis.',
  '8103: Tic, convulsive.',
  '6260: Tinnitus, recurrent.',
  '7535: Toxic nephropathy.',
  '8045: Traumatic brain injury residuals.',
  '6843: Traumatic chest wall defect.',
  '7710: Tuberculosis, adenitis.',
  '5001: Tuberculosis, bones and joints.',
  '6010: Tuberculosis, eye.',
  '7505: Tuberculosis, kidney.',
  '7811: Tuberculosis, luposa (lupus vulgaris).',
  '6311: Tuberculosis, miliary.',
  '6732: Tuberculosis, pleurisy, active or inactive.',
  '6701: Tuberculosis, pulmonary, active, far advanced.',
  '6702: Tuberculosis, pulmonary, active, moderately advanced.',
  '6703: Tuberculosis, pulmonary, active, minimal.',
  '6704: Tuberculosis, pulmonary, active, advancement unspecified.',
  '6730: Tuberculosis, pulmonary, active, chronic.',
  '6731: Tuberculosis, pulmonary, inactive, chronic.',
  '6721: Tuberculosis, pulmonary, inactive, far advanced.',
  '6722: Tuberculosis, pulmonary, inactive, moderately advanced.',
  '6723: Tuberculosis, pulmonary, inactive, minimal.',
  '6724: Tuberculosis, pulmonary, inactive, advancement unspecified.',
  '6211: Tympanic membrane.',
  '7304: Ulcer, peptic.',
  '7511: Ureter, stricture of.',
  '7519: Urethra, fistula.',
  '7518: Urethra, stricture.',
  '7825: Urticaria, chronic.',
  '7611: Vagina, disease or injury.',
  '7348: Vagotomy.',
  '7000: Valvular heart disease.',
  '7543: Varicocele/Hydrocele.',
  '7120: Varicose veins.',
  '7826: Vasculitis, primary cutaneous.',
  '7011: Ventricular arrhythmia.',
  '5235: Vertebral fracture or dislocation.',
  '6300: Vibriosis (Cholera, Non-cholera).',
  '6301: Visceral Leishmaniasis.',
  '7342: Visceroptosis.',
  '6071: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 5/200 (1.5/60).',
  '6072: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6073: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6074: Vision, one eye 5/200 (1.5/60), with visual acuity of other eye 20/40 (6/12).',
  '6075: Vision, one eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60), with visual acuity of other eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60).',
  '6076: Vision, one eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60), with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6077: Vision, one eye 10/200 (3/60), 15/200 (4.5/60), or 20/200 (6/60), with visual acuity of other eye 20/40 (6/12).',
  '6078: Vision, one eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15), with visual acuity of other eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15).',
  '6079: Vision, one eye 20/100 (6/30), 20/70 (6/21), or 20/50 (6/15), with visual acuity of other eye 20/40 (6/12); or each eye 20/40 (6/12).',
  '7823: Vitiligo.',
  '7610: Vulva or clitoris, disease or injury of.',
  '5277: Weak foot.',
  '6335: West Nile virus infection.',
];

export const formsIdList = [
  {
    formId: 'fillform',
    formTitle: 'Submit Intent to File',
    formUrl: '/forms/submit-to-intent',
  },

  {
    formId: 'requestcfile',
    formTitle: 'Request C-File/DD 214 (Form 20-10206)',
    formUrl: '/forms/request-c-file',
  },

  {
    formId: 'ptsdform',
    formTitle: 'PTSD Stressor Statement (Form 21-0781)',
    formUrl: '/forms/ptsd-stressor',
  },
  {
    formId: 'supportofclaim',
    formTitle: 'Statement in Support of Claim (Form 21-4138)',
    formUrl: '/forms/support-claim',
  },
  {
    formId: 'medicalrecords',
    formTitle: 'Medical Records Release (Form 21-4142)',
    formUrl: '/forms/medical-records',
  },
  {
    formId: 'tdiuform',
    formTitle: 'Increased Rating due to TDIU (Unemployability) (Form 21-8940)',
    formUrl: '/forms/tdiu',
  },

  {
    formId: 'higherlevelreview',
    formTitle: 'Higher Level Review (Form 20-0996)',
    formUrl: '/forms/higher-level-review',
  },
  {
    formId: 'boardappeal',
    formTitle: 'Board Appeal (Form 10182)',
    formUrl: '/forms/board-appeal',
  },
  {
    formId: 'supplementalclaimAppeal',
    formTitle: 'Supplemental Claim Appeal',
    formUrl: '/forms/supplemental-claim',
  },

  {
    formId: 'courtform',
    formTitle: 'Notice of Appeal (NOA) & Optional Fee Waiver',
    formUrl: '/forms/noa',
  },
  {
    formId: 'financial_hardship',
    formTitle: 'Declaration of Financial Hardship (Fee Waiver)',
    formUrl: '/forms/fee-waiver',
  },

  {
    formId: 'newclaim',
    formTitle: 'New Claim or Increase (Form 21-526EZ)',
    formUrl: '/forms/new-claim',
  },
  {
    formId: 'supplementalclaim',
    formTitle: 'Supplemental Claim & Reopening (Form 20-0995)',
    formUrl: '/forms/supplemnetal-claim-reopening',
  },
];


export const CompensationRateData = [
  {
      "cola_year": "2025",
      "effective_date": "2024-12-01",
      "rates": {
        "10%": {
          "flat": 175.51
        },
        "20%": {
          "flat": 346.95
        },
        "30%": {
          "base": {
            "veteran_alone": 537.42,
            "veteran_spouse": 601.42,
            "veteran_spouse_one_parent": 652.42,
            "veteran_spouse_two_parents": 703.42,
            "veteran_one_parent": 588.42,
            "veteran_two_parents": 639.42,
            "veteran_one_child": 579.42,
            "veteran_spouse_one_child": 648.42,
            "veteran_spouse_one_parent_one_child": 699.42,
            "veteran_spouse_two_parents_one_child": 750.42,
            "veteran_one_parent_one_child": 630.42,
            "veteran_two_parents_one_child": 681.42
          },
          "addons": {
            "additional_child_under_18": 31.00,
            "additional_child_over_18_school": 102.00,
            "spouse_aid_and_attendance": 58.00
          }
        },
        "40%": {
          "base": {
            "veteran_alone": 774.16,
            "veteran_spouse": 859.16,
            "veteran_spouse_one_parent": 927.16,
            "veteran_spouse_two_parents": 995.16,
            "veteran_one_parent": 842.16,
            "veteran_two_parents": 910.16,
            "veteran_one_child": 831.16,
            "veteran_spouse_one_child": 922.16,
            "veteran_spouse_one_parent_one_child": 990.16,
            "veteran_spouse_two_parents_one_child": 1058.16,
            "veteran_one_parent_one_child": 899.16,
            "veteran_two_parents_one_child": 967.16
          },
          "addons": {
            "additional_child_under_18": 42.00,
            "additional_child_over_18_school": 137.00,
            "spouse_aid_and_attendance": 78.00
          }
        },
        "50%": {
          "base": {
            "veteran_alone": 1102.04,
            "veteran_spouse": 1208.04,
            "veteran_spouse_one_parent": 1293.04,
            "veteran_spouse_two_parents": 1378.04,
            "veteran_one_parent": 1187.04,
            "veteran_two_parents": 1272.04,
            "veteran_one_child": 1173.04,
            "veteran_spouse_one_child": 1287.04,
            "veteran_spouse_one_parent_one_child": 1372.04,
            "veteran_spouse_two_parents_one_child": 1457.04,
            "veteran_one_parent_one_child": 1258.04,
            "veteran_two_parents_one_child": 1343.04
          },
          "addons": {
            "additional_child_under_18": 53.00,
            "additional_child_over_18_school": 171.00,
            "spouse_aid_and_attendance": 98.00
          }
        },
        "60%": {
          "base": {
            "veteran_alone": 1395.93,
            "veteran_spouse": 1523.93,
            "veteran_spouse_one_parent": 1625.93,
            "veteran_spouse_two_parents": 1727.93,
            "veteran_one_parent": 1497.93,
            "veteran_two_parents": 1599.93,
            "veteran_one_child": 1480.93,
            "veteran_spouse_one_child": 1617.93,
            "veteran_spouse_one_parent_one_child": 1719.93,
            "veteran_spouse_two_parents_one_child": 1821.93,
            "veteran_one_parent_one_child": 1582.93,
            "veteran_two_parents_one_child": 1684.93
          },
          "addons": {
            "additional_child_under_18": 63.00,
            "additional_child_over_18_school": 205.00,
            "spouse_aid_and_attendance": 117.00
          }
        },
        "70%": {
          "base": {
            "veteran_alone": 1759.19,
            "veteran_spouse": 1908.19,
            "veteran_spouse_one_parent": 2028.19,
            "veteran_spouse_two_parents": 2148.19,
            "veteran_one_parent": 1879.19,
            "veteran_two_parents": 1999.19,
            "veteran_one_child": 1858.19,
            "veteran_spouse_one_child": 2018.19,
            "veteran_spouse_one_parent_one_child": 2138.19,
            "veteran_spouse_two_parents_one_child": 2258.19,
            "veteran_one_parent_one_child": 1978.19,
            "veteran_two_parents_one_child": 2098.19
          },
          "addons": {
            "additional_child_under_18": 74.00,
            "additional_child_over_18_school": 239.00,
            "spouse_aid_and_attendance": 137.00
          }
        },
        "80%": {
          "base": {
            "veteran_alone": 2044.89,
            "veteran_spouse": 2214.89,
            "veteran_spouse_one_parent": 2351.89,
            "veteran_spouse_two_parents": 2488.89,
            "veteran_one_parent": 2181.89,
            "veteran_two_parents": 2318.89,
            "veteran_one_child": 2158.89,
            "veteran_spouse_one_child": 2340.89,
            "veteran_spouse_one_parent_one_child": 2477.89,
            "veteran_spouse_two_parents_one_child": 2614.89,
            "veteran_one_parent_one_child": 2295.89,
            "veteran_two_parents_one_child": 2432.89
          },
          "addons": {
            "additional_child_under_18": 84.00,
            "additional_child_over_18_school": 274.00,
            "spouse_aid_and_attendance": 157.00
          }
        },
        "90%": {
          "base": {
            "veteran_alone": 2297.96,
            "veteran_spouse": 2489.96,
            "veteran_spouse_one_parent": 2643.96,
            "veteran_spouse_two_parents": 2797.96,
            "veteran_one_parent": 2451.96,
            "veteran_two_parents": 2605.96,
            "veteran_one_child": 2425.96,
            "veteran_spouse_one_child": 2630.96,
            "veteran_spouse_one_parent_one_child": 2784.96,
            "veteran_spouse_two_parents_one_child": 2938.96,
            "veteran_one_parent_one_child": 2579.96,
            "veteran_two_parents_one_child": 2733.96
          },
          "addons": {
            "additional_child_under_18": 95.00,
            "additional_child_over_18_school": 308.00,
            "spouse_aid_and_attendance": 176.00
          }
        },
        "100%": {
          "base": {
            "veteran_alone": 3831.30,
            "veteran_spouse": 4044.91,
            "veteran_spouse_one_parent": 4216.35,
            "veteran_spouse_two_parents": 4387.79,
            "veteran_one_parent": 4002.74,
            "veteran_two_parents": 4174.18,
            "veteran_one_child": 3974.15,
            "veteran_spouse_one_child": 4201.35,
            "veteran_spouse_one_parent_one_child": 4372.79,
            "veteran_spouse_two_parents_one_child": 4544.23,
            "veteran_one_parent_one_child": 4145.59,
            "veteran_two_parents_one_child": 4317.03
          },
          "addons": {
            "additional_child_under_18": 106.14,
            "additional_child_over_18_school": 342.85,
            "spouse_aid_and_attendance": 195.92
          }
        }
      }
  }, 

  {
      "cola_year": "2024",
      "effective_date": "2023-12-01",
      "rates": {
        "10%": {
          "flat": 171.23
        },
        "20%": {
          "flat": 338.49
        },
        "30%": {
          "base": {
            "veteran_alone": 524.31,
            "veteran_spouse": 586.31,
            "veteran_spouse_one_parent": 636.31,
            "veteran_spouse_two_parents": 686.31,
            "veteran_one_parent": 574.31,
            "veteran_two_parents": 624.31,
            "veteran_one_child": 565.31,
            "veteran_spouse_one_child": 632.31,
            "veteran_spouse_one_parent_one_child": 682.31,
            "veteran_spouse_two_parents_one_child": 732.31,
            "veteran_one_parent_one_child": 615.31,
            "veteran_two_parents_one_child": 665.31
          },
          "addons": {
            "additional_child_under_18": 31.00,
            "additional_child_over_18_school": 100.00,
            "spouse_aid_and_attendance": 57.00
          }
        },
        "40%": {
          "base": {
            "veteran_alone": 755.28,
            "veteran_spouse": 838.28,
            "veteran_spouse_one_parent": 904.28,
            "veteran_spouse_two_parents": 970.28,
            "veteran_one_parent": 821.28,
            "veteran_two_parents": 887.28,
            "veteran_one_child": 810.28,
            "veteran_spouse_one_child": 899.28,
            "veteran_spouse_one_parent_one_child": 965.28,
            "veteran_spouse_two_parents_one_child": 1031.28,
            "veteran_one_parent_one_child": 876.28,
            "veteran_two_parents_one_child": 942.28
          },
          "addons": {
            "additional_child_under_18": 41.00,
            "additional_child_over_18_school": 133.00,
            "spouse_aid_and_attendance": 76.00
          }
        },
        "50%": {
          "base": {
            "veteran_alone": 1075.16,
            "veteran_spouse": 1179.16,
            "veteran_spouse_one_parent": 1262.16,
            "veteran_spouse_two_parents": 1345.16,
            "veteran_one_parent": 1160.16,
            "veteran_two_parents": 1243.16,
            "veteran_one_child": 1144.16,
            "veteran_spouse_one_child": 1255.16,
            "veteran_spouse_one_parent_one_child": 1338.16,
            "veteran_spouse_two_parents_one_child": 1421.16,
            "veteran_one_parent_one_child": 1229.16,
            "veteran_two_parents_one_child": 1312.16
          },
          "addons": {
            "additional_child_under_18": 51.00,
            "additional_child_over_18_school": 167.00,
            "spouse_aid_and_attendance": 95.00
          }
        },
        "60%": {
          "base": {
            "veteran_alone": 1361.88,
            "veteran_spouse": 1486.88,
            "veteran_spouse_one_parent": 1586.88,
            "veteran_spouse_two_parents": 1686.88,
            "veteran_one_parent": 1461.88,
            "veteran_two_parents": 1561.88,
            "veteran_one_child": 1444.88,
            "veteran_spouse_one_child": 1577.88,
            "veteran_spouse_one_parent_one_child": 1677.88,
            "veteran_spouse_two_parents_one_child": 1777.88,
            "veteran_one_parent_one_child": 1544.88,
            "veteran_two_parents_one_child": 1644.88
          },
          "addons": {
            "additional_child_under_18": 62.00,
            "additional_child_over_18_school": 200.00,
            "spouse_aid_and_attendance": 114.00
          }
        },
        "70%": {
          "base": {
            "veteran_alone": 1716.28,
            "veteran_spouse": 1861.28,
            "veteran_spouse_one_parent": 1978.28,
            "veteran_spouse_two_parents": 2095.28,
            "veteran_one_parent": 1833.28,
            "veteran_two_parents": 1950.28,
            "veteran_one_child": 1813.28,
            "veteran_spouse_one_child": 1968.28,
            "veteran_spouse_one_parent_one_child": 2085.28,
            "veteran_spouse_two_parents_one_child": 2202.28,
            "veteran_one_parent_one_child": 1930.28,
            "veteran_two_parents_one_child": 2047.28
          },
          "addons": {
            "additional_child_under_18": 68.00,
            "additional_child_over_18_school": 221.00,
            "spouse_aid_and_attendance": 134.00
          }
        },
        "80%": {
          "base": {
            "veteran_alone": 1995.01,
            "veteran_spouse": 2161.01,
            "veteran_spouse_one_parent": 2294.01,
            "veteran_spouse_two_parents": 2427.01,
            "veteran_one_parent": 2128.01,
            "veteran_two_parents": 2261.01,
            "veteran_one_child": 2106.01,
            "veteran_spouse_one_child": 2283.01,
            "veteran_spouse_one_parent_one_child": 2416.01,
            "veteran_spouse_two_parents_one_child": 2549.01,
            "veteran_one_parent_one_child": 2239.01,
            "veteran_two_parents_one_child": 2372.01
          },
          "addons": {
            "additional_child_under_18": 77.00,
            "additional_child_over_18_school": 250.00,
            "spouse_aid_and_attendance": 153.00
          }
        },
        "90%": {
          "base": {
            "veteran_alone": 2241.91,
            "veteran_spouse": 2428.91,
            "veteran_spouse_one_parent": 2578.91,
            "veteran_spouse_two_parents": 2728.91,
            "veteran_one_parent": 2391.91,
            "veteran_two_parents": 2541.91,
            "veteran_one_child": 2366.91,
            "veteran_spouse_one_child": 2565.91,
            "veteran_spouse_one_parent_one_child": 2715.91,
            "veteran_spouse_two_parents_one_child": 2865.91,
            "veteran_one_parent_one_child": 2516.91,
            "veteran_two_parents_one_child": 2666.91
          },
          "addons": {
            "additional_child_under_18": 86.00,
            "additional_child_over_18_school": 279.00,
            "spouse_aid_and_attendance": 172.00
          }
        },
        "100%": {
          "base": {
            "veteran_alone": 3737.85,
            "veteran_spouse": 3946.25,
            "veteran_spouse_one_parent": 4113.51,
            "veteran_spouse_two_parents": 4280.77,
            "veteran_one_parent": 3905.11,
            "veteran_two_parents": 4072.37,
            "veteran_one_child": 3877.22,
            "veteran_spouse_one_child": 4098.87,
            "veteran_spouse_one_parent_one_child": 4266.13,
            "veteran_spouse_two_parents_one_child": 4433.39,
            "veteran_one_parent_one_child": 4045.47,
            "veteran_two_parents_one_child": 4212.73
          },
          "addons": {
            "additional_child_under_18": 97.00,
            "additional_child_over_18_school": 313.00,
            "spouse_aid_and_attendance": 191.14
          }
        }
      }
  }, 

  {
      "cola_year": "2023",
      "effective_date": "2022-12-01",
      "rates": {
        "10%": {
          "flat": 165.92
        },
        "20%": {
          "flat": 327.99
        },
        "30%": {
          "base": {
            "veteran_alone": 508.05,
            "veteran_spouse": 568.05,
            "veteran_spouse_one_parent": 616.05,
            "veteran_spouse_two_parents": 664.05,
            "veteran_one_parent": 556.05,
            "veteran_two_parents": 604.05,
            "veteran_one_child": 548.05,
            "veteran_spouse_one_child": 612.05,
            "veteran_spouse_one_parent_one_child": 660.05,
            "veteran_spouse_two_parents_one_child": 708.05,
            "veteran_one_parent_one_child": 596.05,
            "veteran_two_parents_one_child": 644.05
          },
          "addons": {
            "additional_child_under_18": 30.00,
            "additional_child_over_18_school": 97.00,
            "spouse_aid_and_attendance": 55.00
          }
        },
        "40%": {
          "base": {
            "veteran_alone": 731.86,
            "veteran_spouse": 811.86,
            "veteran_spouse_one_parent": 875.86,
            "veteran_spouse_two_parents": 939.86,
            "veteran_one_parent": 795.86,
            "veteran_two_parents": 859.86,
            "veteran_one_child": 785.86,
            "veteran_spouse_one_child": 870.86,
            "veteran_spouse_one_parent_one_child": 934.86,
            "veteran_spouse_two_parents_one_child": 998.86,
            "veteran_one_parent_one_child": 849.86,
            "veteran_two_parents_one_child": 913.86
          },
          "addons": {
            "additional_child_under_18": 39.00,
            "additional_child_over_18_school": 129.00,
            "spouse_aid_and_attendance": 74.00
          }
        },
        "50%": {
          "base": {
            "veteran_alone": 1041.82,
            "veteran_spouse": 1141.82,
            "veteran_spouse_one_parent": 1222.82,
            "veteran_spouse_two_parents": 1303.82,
            "veteran_one_parent": 1122.82,
            "veteran_two_parents": 1203.82,
            "veteran_one_child": 1108.82,
            "veteran_spouse_one_child": 1215.82,
            "veteran_spouse_one_parent_one_child": 1296.82,
            "veteran_spouse_two_parents_one_child": 1377.82,
            "veteran_one_parent_one_child": 1189.82,
            "veteran_two_parents_one_child": 1270.82
          },
          "addons": {
            "additional_child_under_18": 50.00,
            "additional_child_over_18_school": 162.00,
            "spouse_aid_and_attendance": 92.00
          }
        },
        "60%": {
          "base": {
            "veteran_alone": 1319.65,
            "veteran_spouse": 1440.65,
            "veteran_spouse_one_parent": 1537.65,
            "veteran_spouse_two_parents": 1634.65,
            "veteran_one_parent": 1416.65,
            "veteran_two_parents": 1513.65,
            "veteran_one_child": 1400.65,
            "veteran_spouse_one_child": 1528.65,
            "veteran_spouse_one_parent_one_child": 1625.65,
            "veteran_spouse_two_parents_one_child": 1722.65,
            "veteran_one_parent_one_child": 1497.65,
            "veteran_two_parents_one_child": 1594.65
          },
          "addons": {
            "additional_child_under_18": 60.00,
            "additional_child_over_18_school": 194.00,
            "spouse_aid_and_attendance": 111.00
          }
        },
        "70%": {
          "base": {
            "veteran_alone": 1663.06,
            "veteran_spouse": 1804.06,
            "veteran_spouse_one_parent": 1917.06,
            "veteran_spouse_two_parents": 2030.06,
            "veteran_one_parent": 1776.06,
            "veteran_two_parents": 1889.06,
            "veteran_one_child": 1757.06,
            "veteran_spouse_one_child": 1907.06,
            "veteran_spouse_one_parent_one_child": 2020.06,
            "veteran_spouse_two_parents_one_child": 2133.06,
            "veteran_one_parent_one_child": 1870.06,
            "veteran_two_parents_one_child": 1983.06
          },
          "addons": {
            "additional_child_under_18": 70.00,
            "additional_child_over_18_school": 226.00,
            "spouse_aid_and_attendance": 130.00
          }
        },
        "80%": {
          "base": {
            "veteran_alone": 1933.15,
            "veteran_spouse": 2094.15,
            "veteran_spouse_one_parent": 2223.15,
            "veteran_spouse_two_parents": 2353.15,
            "veteran_one_parent": 2062.15,
            "veteran_two_parents": 2191.15,
            "veteran_one_child": 2041.15,
            "veteran_spouse_one_child": 2212.15,
            "veteran_spouse_one_parent_one_child": 2341.15,
            "veteran_spouse_two_parents_one_child": 2470.15,
            "veteran_one_parent_one_child": 2170.15,
            "veteran_two_parents_one_child": 2299.15
          },
          "addons": {
            "additional_child_under_18": 80.00,
            "additional_child_over_18_school": 259.00,
            "spouse_aid_and_attendance": 148.00
          }
        },
        "90%": {
          "base": {
            "veteran_alone": 2172.39,
            "veteran_spouse": 2353.39,
            "veteran_spouse_one_parent": 2498.39,
            "veteran_spouse_two_parents": 2643.39,
            "veteran_one_parent": 2317.39,
            "veteran_two_parents": 2462.39,
            "veteran_one_child": 2293.39,
            "veteran_spouse_one_child": 2486.39,
            "veteran_spouse_one_parent_one_child": 2631.39,
            "veteran_spouse_two_parents_one_child": 2776.39,
            "veteran_one_parent_one_child": 2438.39,
            "veteran_two_parents_one_child": 2583.39
          },
          "addons": {
            "additional_child_under_18": 90.00,
            "additional_child_over_18_school": 291.00,
            "spouse_aid_and_attendance": 167.00
          }
        },
        "100%": {
          "base": {
            "veteran_alone": 3621.95,
            "veteran_spouse": 3823.89,
            "veteran_spouse_one_parent": 3985.96,
            "veteran_spouse_two_parents": 4148.03,
            "veteran_one_parent": 3784.02,
            "veteran_two_parents": 3946.09,
            "veteran_one_child": 3753.02,
            "veteran_spouse_one_child": 3974.66,
            "veteran_spouse_one_parent_one_child": 4136.73,
            "veteran_spouse_two_parents_one_child": 4298.80,
            "veteran_one_parent_one_child": 3915.09,
            "veteran_two_parents_one_child": 4077.16
          },
          "addons": {
            "additional_child_under_18": 94.00,
            "additional_child_over_18_school": 304.00,
            "spouse_aid_and_attendance": 185.00
          }
        }
      }
  }, 

  {
      "cola_year": "2022",
      "effective_date": "2021-12-01",
      "rates": {
        "10%": {
          "flat": 152.64
        },
        "20%": {
          "flat": 301.74
        },
        "30%": {
          "base": {
            "veteran_alone": 467.39,
            "veteran_spouse": 522.39,
            "veteran_spouse_one_parent": 566.39,
            "veteran_spouse_two_parents": 610.39,
            "veteran_one_parent": 511.39,
            "veteran_two_parents": 555.39,
            "veteran_one_child": 504.39,
            "veteran_spouse_one_child": 563.39,
            "veteran_spouse_one_parent_one_child": 607.39,
            "veteran_spouse_two_parents_one_child": 651.39,
            "veteran_one_parent_one_child": 548.39,
            "veteran_two_parents_one_child": 592.39
          },
          "addons": {
            "additional_child_under_18": 27.00,
            "additional_child_over_18_school": 89.00,
            "spouse_aid_and_attendance": 51.00
          }
        },
        "40%": {
          "base": {
            "veteran_alone": 673.28,
            "veteran_spouse": 747.28,
            "veteran_spouse_one_parent": 806.28,
            "veteran_spouse_two_parents": 865.28,
            "veteran_one_parent": 732.28,
            "veteran_two_parents": 791.28,
            "veteran_one_child": 722.28,
            "veteran_spouse_one_child": 801.28,
            "veteran_spouse_one_parent_one_child": 860.28,
            "veteran_spouse_two_parents_one_child": 919.28,
            "veteran_one_parent_one_child": 781.28,
            "veteran_two_parents_one_child": 840.28
          },
          "addons": {
            "additional_child_under_18": 36.00,
            "additional_child_over_18_school": 119.00,
            "spouse_aid_and_attendance": 68.00
          }
        },
        "50%": {
          "base": {
            "veteran_alone": 958.44,
            "veteran_spouse": 1050.44,
            "veteran_spouse_one_parent": 1124.44,
            "veteran_spouse_two_parents": 1198.44,
            "veteran_one_parent": 1032.44,
            "veteran_two_parents": 1106.44,
            "veteran_one_child": 1020.44,
            "veteran_spouse_one_child": 1118.44,
            "veteran_spouse_one_parent_one_child": 1192.44,
            "veteran_spouse_two_parents_one_child": 1266.44,
            "veteran_one_parent_one_child": 1094.44,
            "veteran_two_parents_one_child": 1168.44
          },
          "addons": {
            "additional_child_under_18": 46.00,
            "additional_child_over_18_school": 149.00,
            "spouse_aid_and_attendance": 86.00
          }
        },
        "60%": {
          "base": {
            "veteran_alone": 1213.27,
            "veteran_spouse": 1326.27,
            "veteran_spouse_one_parent": 1415.27,
            "veteran_spouse_two_parents": 1504.27,
            "veteran_one_parent": 1302.27,
            "veteran_two_parents": 1391.27,
            "veteran_one_child": 1289.27,
            "veteran_spouse_one_child": 1410.27,
            "veteran_spouse_one_parent_one_child": 1499.27,
            "veteran_spouse_two_parents_one_child": 1588.27,
            "veteran_one_parent_one_child": 1378.27,
            "veteran_two_parents_one_child": 1467.27
          },
          "addons": {
            "additional_child_under_18": 55.00,
            "additional_child_over_18_school": 178.00,
            "spouse_aid_and_attendance": 103.00
          }
        },
        "70%": {
          "base": {
            "veteran_alone": 1529.61,
            "veteran_spouse": 1659.61,
            "veteran_spouse_one_parent": 1763.61,
            "veteran_spouse_two_parents": 1867.61,
            "veteran_one_parent": 1633.61,
            "veteran_two_parents": 1737.61,
            "veteran_one_child": 1613.61,
            "veteran_spouse_one_child": 1755.61,
            "veteran_spouse_one_parent_one_child": 1859.61,
            "veteran_spouse_two_parents_one_child": 1963.61,
            "veteran_one_parent_one_child": 1717.61,
            "veteran_two_parents_one_child": 1821.61
          },
          "addons": {
            "additional_child_under_18": 64.00,
            "additional_child_over_18_school": 207.00,
            "spouse_aid_and_attendance": 119.00
          }
        },
        "80%": {
          "base": {
            "veteran_alone": 1775.79,
            "veteran_spouse": 1920.79,
            "veteran_spouse_one_parent": 2040.79,
            "veteran_spouse_two_parents": 2160.79,
            "veteran_one_parent": 1895.79,
            "veteran_two_parents": 2015.79,
            "veteran_one_child": 1870.79,
            "veteran_spouse_one_child": 2028.79,
            "veteran_spouse_one_parent_one_child": 2148.79,
            "veteran_spouse_two_parents_one_child": 2268.79,
            "veteran_one_parent_one_child": 1990.79,
            "veteran_two_parents_one_child": 2110.79
          },
          "addons": {
            "additional_child_under_18": 73.00,
            "additional_child_over_18_school": 237.00,
            "spouse_aid_and_attendance": 136.00
          }
        },
        "90%": {
          "base": {
            "veteran_alone": 1993.12,
            "veteran_spouse": 2157.12,
            "veteran_spouse_one_parent": 2289.12,
            "veteran_spouse_two_parents": 2421.12,
            "veteran_one_parent": 2125.12,
            "veteran_two_parents": 2257.12,
            "veteran_one_child": 2101.12,
            "veteran_spouse_one_child": 2280.12,
            "veteran_spouse_one_parent_one_child": 2412.12,
            "veteran_spouse_two_parents_one_child": 2544.12,
            "veteran_one_parent_one_child": 2233.12,
            "veteran_two_parents_one_child": 2365.12
          },
          "addons": {
            "additional_child_under_18": 82.00,
            "additional_child_over_18_school": 266.00,
            "spouse_aid_and_attendance": 153.00
          }
        },
        "100%": {
          "base": {
            "veteran_alone": 3507.01,
            "veteran_spouse": 3697.01,
            "veteran_spouse_one_parent": 3853.01,
            "veteran_spouse_two_parents": 4009.01,
            "veteran_one_parent": 3663.01,
            "veteran_two_parents": 3819.01,
            "veteran_one_child": 3640.01,
            "veteran_spouse_one_child": 3854.01,
            "veteran_spouse_one_parent_one_child": 4010.01,
            "veteran_spouse_two_parents_one_child": 4166.01,
            "veteran_one_parent_one_child": 3796.01,
            "veteran_two_parents_one_child": 3952.01
          },
          "addons": {
            "additional_child_under_18": 91.00,
            "additional_child_over_18_school": 294.00,
            "spouse_aid_and_attendance": 168.00
          }
        }
      }
  },

  {
      "cola_year": "2021",
      "effective_date": "2020-12-01",
      "rates": {
        "10%": {
          "flat": 144.14
        },
        "20%": {
          "flat": 284.93
        },
        "30%": {
          "base": {
            "veteran_alone": 441.35,
            "veteran_spouse": 493.35,
            "veteran_spouse_one_parent": 535.35,
            "veteran_spouse_two_parents": 577.35,
            "veteran_one_parent": 483.35,
            "veteran_two_parents": 525.35,
            "veteran_one_child": 476.35,
            "veteran_spouse_one_child": 532.35,
            "veteran_spouse_one_parent_one_child": 574.35,
            "veteran_spouse_two_parents_one_child": 616.35,
            "veteran_one_parent_one_child": 518.35,
            "veteran_two_parents_one_child": 560.35
          },
          "addons": {
            "additional_child_under_18": 26.00,
            "additional_child_over_18_school": 84.00,
            "spouse_aid_and_attendance": 48.00
          }
        },
        "40%": {
          "base": {
            "veteran_alone": 635.77,
            "veteran_spouse": 705.77,
            "veteran_spouse_one_parent": 761.77,
            "veteran_spouse_two_parents": 817.77,
            "veteran_one_parent": 691.77,
            "veteran_two_parents": 747.77,
            "veteran_one_child": 681.77,
            "veteran_spouse_one_child": 756.77,
            "veteran_spouse_one_parent_one_child": 812.77,
            "veteran_spouse_two_parents_one_child": 868.77,
            "veteran_one_parent_one_child": 737.77,
            "veteran_two_parents_one_child": 793.77
          },
          "addons": {
            "additional_child_under_18": 34.00,
            "additional_child_over_18_school": 112.00,
            "spouse_aid_and_attendance": 64.00
          }
        },
        "50%": {
          "base": {
            "veteran_alone": 905.04,
            "veteran_spouse": 992.04,
            "veteran_spouse_one_parent": 1062.04,
            "veteran_spouse_two_parents": 1132.04,
            "veteran_one_parent": 975.04,
            "veteran_two_parents": 1045.04,
            "veteran_one_child": 963.04,
            "veteran_spouse_one_child": 1056.04,
            "veteran_spouse_one_parent_one_child": 1126.04,
            "veteran_spouse_two_parents_one_child": 1196.04,
            "veteran_one_parent_one_child": 1033.04,
            "veteran_two_parents_one_child": 1103.04
          },
          "addons": {
            "additional_child_under_18": 43.00,
            "additional_child_over_18_school": 140.00,
            "spouse_aid_and_attendance": 81.00
          }
        },
        "60%": {
          "base": {
            "veteran_alone": 1146.39,
            "veteran_spouse": 1251.39,
            "veteran_spouse_one_parent": 1335.39,
            "veteran_spouse_two_parents": 1419.39,
            "veteran_one_parent": 1230.39,
            "veteran_two_parents": 1314.39,
            "veteran_one_child": 1216.39,
            "veteran_spouse_one_child": 1326.39,
            "veteran_spouse_one_parent_one_child": 1410.39,
            "veteran_spouse_two_parents_one_child": 1494.39,
            "veteran_one_parent_one_child": 1300.39,
            "veteran_two_parents_one_child": 1384.39
          },
          "addons": {
            "additional_child_under_18": 52.00,
            "additional_child_over_18_school": 169.00,
            "spouse_aid_and_attendance": 97.00
          }
        },
        "70%": {
          "base": {
            "veteran_alone": 1444.86,
            "veteran_spouse": 1569.86,
            "veteran_spouse_one_parent": 1668.86,
            "veteran_spouse_two_parents": 1767.86,
            "veteran_one_parent": 1548.86,
            "veteran_two_parents": 1647.86,
            "veteran_one_child": 1524.86,
            "veteran_spouse_one_child": 1662.86,
            "veteran_spouse_one_parent_one_child": 1761.86,
            "veteran_spouse_two_parents_one_child": 1860.86,
            "veteran_one_parent_one_child": 1628.86,
            "veteran_two_parents_one_child": 1727.86
          },
          "addons": {
            "additional_child_under_18": 60.00,
            "additional_child_over_18_school": 196.00,
            "spouse_aid_and_attendance": 112.00
          }
        },
        "80%": {
          "base": {
            "veteran_alone": 1677.74,
            "veteran_spouse": 1815.74,
            "veteran_spouse_one_parent": 1930.74,
            "veteran_spouse_two_parents": 2045.74,
            "veteran_one_parent": 1792.74,
            "veteran_two_parents": 1907.74,
            "veteran_one_child": 1767.74,
            "veteran_spouse_one_child": 1918.74,
            "veteran_spouse_one_parent_one_child": 2033.74,
            "veteran_spouse_two_parents_one_child": 2148.74,
            "veteran_one_parent_one_child": 1882.74,
            "veteran_two_parents_one_child": 1997.74
          },
          "addons": {
            "additional_child_under_18": 69.00,
            "additional_child_over_18_school": 225.00,
            "spouse_aid_and_attendance": 129.00
          }
        },
        "90%": {
          "base": {
            "veteran_alone": 1881.17,
            "veteran_spouse": 2038.17,
            "veteran_spouse_one_parent": 2165.17,
            "veteran_spouse_two_parents": 2292.17,
            "veteran_one_parent": 2003.17,
            "veteran_two_parents": 2130.17,
            "veteran_one_child": 1984.17,
            "veteran_spouse_one_child": 2154.17,
            "veteran_spouse_one_parent_one_child": 2281.17,
            "veteran_spouse_two_parents_one_child": 2408.17,
            "veteran_one_parent_one_child": 2106.17,
            "veteran_two_parents_one_child": 2233.17
          },
          "addons": {
            "additional_child_under_18": 77.00,
            "additional_child_over_18_school": 252.00,
            "spouse_aid_and_attendance": 144.00
          }
        },
        "100%": {
          "base": {
            "veteran_alone": 3310.30,
            "veteran_spouse": 3493.30,
            "veteran_spouse_one_parent": 3642.30,
            "veteran_spouse_two_parents": 3791.30,
            "veteran_one_parent": 3459.30,
            "veteran_two_parents": 3608.30,
            "veteran_one_child": 3450.30,
            "veteran_spouse_one_child": 3655.30,
            "veteran_spouse_one_parent_one_child": 3804.30,
            "veteran_spouse_two_parents_one_child": 3953.30,
            "veteran_one_parent_one_child": 3599.30,
            "veteran_two_parents_one_child": 3748.30
          },
          "addons": {
            "additional_child_under_18": 86.00,
            "additional_child_over_18_school": 277.00,
            "spouse_aid_and_attendance": 158.00
          }
        }
      }
  },

  {
      "cola_year": "2020",
      "effective_date": "2019-12-01",
      "rates": {
        "10%": {
          "flat": 142.29
        },
        "20%": {
          "flat": 281.27
        },
        "30%": {
          "base": {
            "veteran_alone": 435.69,
            "veteran_spouse": 486.69,
            "veteran_spouse_one_parent": 527.69,
            "veteran_spouse_two_parents": 568.69,
            "veteran_one_parent": 476.69,
            "veteran_two_parents": 517.69,
            "veteran_one_child": 469.69,
            "veteran_spouse_one_child": 525.69,
            "veteran_spouse_one_parent_one_child": 566.69,
            "veteran_spouse_two_parents_one_child": 607.69,
            "veteran_one_parent_one_child": 510.69,
            "veteran_two_parents_one_child": 551.69
          },
          "addons": {
            "additional_child_under_18": 25.00,
            "additional_child_over_18_school": 83.00,
            "spouse_aid_and_attendance": 48.00
          }
        },
        "40%": {
          "base": {
            "veteran_alone": 627.61,
            "veteran_spouse": 696.61,
            "veteran_spouse_one_parent": 751.61,
            "veteran_spouse_two_parents": 806.61,
            "veteran_one_parent": 682.61,
            "veteran_two_parents": 737.61,
            "veteran_one_child": 673.61,
            "veteran_spouse_one_child": 747.61,
            "veteran_spouse_one_parent_one_child": 802.61,
            "veteran_spouse_two_parents_one_child": 857.61,
            "veteran_one_parent_one_child": 728.61,
            "veteran_two_parents_one_child": 783.61
          },
          "addons": {
            "additional_child_under_18": 34.00,
            "additional_child_over_18_school": 111.00,
            "spouse_aid_and_attendance": 63.00
          }
        },
        "50%": {
          "base": {
            "veteran_alone": 893.43,
            "veteran_spouse": 979.43,
            "veteran_spouse_one_parent": 1048.43,
            "veteran_spouse_two_parents": 1117.43,
            "veteran_one_parent": 962.43,
            "veteran_two_parents": 1031.43,
            "veteran_one_child": 950.43,
            "veteran_spouse_one_child": 1043.43,
            "veteran_spouse_one_parent_one_child": 1112.43,
            "veteran_spouse_two_parents_one_child": 1181.43,
            "veteran_one_parent_one_child": 1019.43,
            "veteran_two_parents_one_child": 1088.43
          },
          "addons": {
            "additional_child_under_18": 43.00,
            "additional_child_over_18_school": 138.00,
            "spouse_aid_and_attendance": 80.00
          }
        },
        "60%": {
          "base": {
            "veteran_alone": 1131.68,
            "veteran_spouse": 1234.68,
            "veteran_spouse_one_parent": 1317.68,
            "veteran_spouse_two_parents": 1400.68,
            "veteran_one_parent": 1214.68,
            "veteran_two_parents": 1297.68,
            "veteran_one_child": 1201.68,
            "veteran_spouse_one_child": 1311.68,
            "veteran_spouse_one_parent_one_child": 1394.68,
            "veteran_spouse_two_parents_one_child": 1477.68,
            "veteran_one_parent_one_child": 1284.68,
            "veteran_two_parents_one_child": 1367.68
          },
          "addons": {
            "additional_child_under_18": 51.00,
            "additional_child_over_18_school": 166.00,
            "spouse_aid_and_attendance": 95.00
          }
        },
        "70%": {
          "base": {
            "veteran_alone": 1425.43,
            "veteran_spouse": 1545.43,
            "veteran_spouse_one_parent": 1640.43,
            "veteran_spouse_two_parents": 1735.43,
            "veteran_one_parent": 1525.43,
            "veteran_two_parents": 1620.43,
            "veteran_one_child": 1500.43,
            "veteran_spouse_one_child": 1633.43,
            "veteran_spouse_one_parent_one_child": 1728.43,
            "veteran_spouse_two_parents_one_child": 1823.43,
            "veteran_one_parent_one_child": 1600.43,
            "veteran_two_parents_one_child": 1695.43
          },
          "addons": {
            "additional_child_under_18": 59.00,
            "additional_child_over_18_school": 192.00,
            "spouse_aid_and_attendance": 110.00
          }
        },
        "80%": {
          "base": {
            "veteran_alone": 1655.40,
            "veteran_spouse": 1790.40,
            "veteran_spouse_one_parent": 1902.40,
            "veteran_spouse_two_parents": 2014.40,
            "veteran_one_parent": 1767.40,
            "veteran_two_parents": 1879.40,
            "veteran_one_child": 1742.40,
            "veteran_spouse_one_child": 1889.40,
            "veteran_spouse_one_parent_one_child": 2001.40,
            "veteran_spouse_two_parents_one_child": 2113.40,
            "veteran_one_parent_one_child": 1854.40,
            "veteran_two_parents_one_child": 1966.40
          },
          "addons": {
            "additional_child_under_18": 68.00,
            "additional_child_over_18_school": 221.00,
            "spouse_aid_and_attendance": 127.00
          }
        },
        "90%": {
          "base": {
            "veteran_alone": 1855.22,
            "veteran_spouse": 2009.22,
            "veteran_spouse_one_parent": 2133.22,
            "veteran_spouse_two_parents": 2257.22,
            "veteran_one_parent": 1974.22,
            "veteran_two_parents": 2098.22,
            "veteran_one_child": 1954.22,
            "veteran_spouse_one_child": 2111.22,
            "veteran_spouse_one_parent_one_child": 2235.22,
            "veteran_spouse_two_parents_one_child": 2359.22,
            "veteran_one_parent_one_child": 2073.22,
            "veteran_two_parents_one_child": 2197.22
          },
          "addons": {
            "additional_child_under_18": 76.00,
            "additional_child_over_18_school": 248.00,
            "spouse_aid_and_attendance": 141.00
          }
        },
        "100%": {
          "base": {
            "veteran_alone": 3269.30,
            "veteran_spouse": 3447.30,
            "veteran_spouse_one_parent": 3592.30,
            "veteran_spouse_two_parents": 3737.30,
            "veteran_one_parent": 3414.30,
            "veteran_two_parents": 3559.30,
            "veteran_one_child": 3405.30,
            "veteran_spouse_one_child": 3606.30,
            "veteran_spouse_one_parent_one_child": 3751.30,
            "veteran_spouse_two_parents_one_child": 3896.30,
            "veteran_one_parent_one_child": 3550.30,
            "veteran_two_parents_one_child": 3695.30
          },
          "addons": {
            "additional_child_under_18": 85.00,
            "additional_child_over_18_school": 273.00,
            "spouse_aid_and_attendance": 156.00
          }
        }
      }
  }
  
];