import App from '../../App';
import Head from 'next/head';

const AuthLayout = ({ children, title }) => {
  return (
    <App>
      <Head>
        <title>{title ? title : 'VetEZ'}</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="absolute inset-0">
        <img
          src="/assets/images/bg-gradient.png"
          alt="image"
          className="h-full w-full object-cover"
        />
      </div>
      <div className="relative flex min-h-screen items-center justify-center bg-[url('/assets/images/map.png')] bg-cover bg-center dark:bg-[url('/assets/images/map-dark.svg')]">
        <div className="relative w-full max-w-[870px]">
          <div className="flex flex-col justify-center rounded-md bg-[#006092] px-6 py-20  text-white lg:min-h-[95vh]">
            <div className="mx-auto w-full max-w-[440px]">{children}</div>
          </div>
        </div>
      </div>
    </App>
  );
};

export default AuthLayout;
