import App from '../../App';
import Head from 'next/head';

const BlankLayout = ({ children, title }) => {
  return (
    <App>
      <Head>
        <title>{title ? title : 'VetEZ'}</title>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="min-h-screen text-black dark:text-white-dark">
        {children}{' '}
      </div>
    </App>
  );
};

export default BlankLayout;
